Repository oliverklee/ext-seminars, pull requests merged in 2019-11, with the labels that each got.

#273 [BUGFIX] Explicitly add transitive dependencies
  CHANGELOG.md
  composer.json
Labels: bug, cleanup

#274 [BUGFIX] Explicitly add transitive dependencies
  CHANGELOG.md
  composer.json
Labels: cleanup

#277 [CLEANUP] Sort the Composer dependencies
  CHANGELOG.md
  composer.json
Labels: cleanup

#280 [CLEANUP] Drop the unused icons
  CHANGELOG.md
  Resources/Public/Icons/EventComplete__h.gif
  Resources/Public/Icons/EventComplete__t.gif
  Resources/Public/Icons/EventDate__h.gif
  Resources/Public/Icons/EventDate__t.gif
  Resources/Public/Icons/EventTopic__h.gif
  Resources/Public/Icons/EventTopic__t.gif
  Resources/Public/Icons/Registration__h.gif
  ext_icon.svg
Labels: cleanup

#281 [BUGFIX] Fix bogus sorting value in some test cases
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
Labels: bug

#282 [BUGFIX] Fix another bogus sorting value in a test case
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
Labels: bug

#286 [BUGFIX] Fix strict type errors in the tests
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
Labels: bug, cleanup

#288 [CLEANUP] Drop obsolete comment code block
  Classes/Hooks/RegistrationEmailHookInterface.php
Labels: cleanup

#287 [BUGFIX] Only use strings in string functions
  CHANGELOG.md
  Classes/BagBuilder/Category.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/OldModel/Abstract.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
Labels: bug, cleanup

#289 [CLEANUP] Fix the PHPDoc type annotations
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Classes/Csv/AbstractRegistrationListView.php
  Classes/Csv/EventListView.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Mapper/Event.php
  Classes/Model/Checkbox.php
  Classes/Model/Event.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Place.php
  Classes/Model/Registration.php
  Classes/Model/Speaker.php
  Classes/Model/TargetGroup.php
  Classes/Model/TimeSlot.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/RegistrationManager.php
  Classes/Service/SingleViewLinkBuilder.php
Labels: bug, cleanup

#290 [CLEANUP] Clean up switch/case constructs
  Classes/BagBuilder/Event.php
  Classes/FrontEnd/DefaultController.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
Labels: cleanup

#291 [CLEANUP] Use !== null for non-null checks
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Place.php
Labels: cleanup

#292 [BUGFIX] Fix type errors concerning integers
  CHANGELOG.md
  Classes/Bag/Abstract.php
  Classes/BagBuilder/Event.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/OldModel/Abstract.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
Labels: bug, cleanup

#293 [CLEANUP] Fix more PHPDoc type annotations
  CHANGELOG.md
  Classes/OldModel/Event.php
  Classes/Service/RegistrationManager.php
  Classes/Service/SingleViewLinkBuilder.php
Labels: bug, cleanup

#294 [BUGFIX] Strictly require types for AbstractBagBuilder::setSourcePages
  CHANGELOG.md
  Classes/BackEnd/EventsList.php
  Classes/BackEnd/OrganizersList.php
  Classes/BackEnd/RegistrationsList.php
  Classes/BackEnd/SpeakersList.php
  Classes/BagBuilder/Abstract.php
  Classes/Csv/AbstractRegistrationListView.php
  Classes/Csv/EventListView.php
  Tests/LegacyUnit/BagBuilder/AbstractTest.php
Labels: bug, cleanup

#295 [BUGFIX] Always provide flags to htmlspecialchars
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/EventsList.php
  Classes/BackEnd/OrganizersList.php
  Classes/BackEnd/RegistrationsList.php
  Classes/BackEnd/SpeakersList.php
  Classes/ConfigCheck.php
  Classes/FrontEnd/CategoryList.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventHeadline.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/Service/RegistrationManager.php
  Classes/ViewHelper/CommaSeparatedTitles.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventHeadlineTest.php
  Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
  Tests/LegacyUnit/ViewHelper/CommaSeparatedTitlesTest.php
Labels: bug

#296 [BUGFIX] Expect integer UIDs for `recordExists`
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/OldModel/Abstract.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: bug, cleanup

#297 [BUGFIX] Fix strict type errors for strings
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/Event.php
  Classes/SchedulerTasks/RegistrationDigest.php
  Classes/Service/RegistrationManager.php
  Classes/Service/SingleViewLinkBuilder.php
Labels: bug, cleanup

#298 [CLEANUP] Expect int as parameter for canRegisterSeats
  CHANGELOG.md
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#299 [CLEANUP] Use the null coalesce operator
  CHANGELOG.md
  Classes/FrontEnd/Editor.php
  Classes/FrontEnd/EventEditor.php
  Classes/OldModel/Event.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/MailNotifierConfiguration.php
  Classes/Service/EmailService.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierConfigurationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
Labels: cleanup

#301 [CLEANUP] Use return type declarations in the tests
  CHANGELOG.md
  Tests/Functional/Configuration/TypoScriptSetupTest.php
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/OldModel/SpeakerTest.php
  Tests/Functional/RealUrl/ConfigurationTest.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EventListViewTest.php
  Tests/LegacyUnit/Fixtures/BackEnd/TestingEventMailForm.php
  Tests/LegacyUnit/Fixtures/BagBuilder/Testing.php
  Tests/LegacyUnit/Fixtures/DummyObjectToCheck.php
  Tests/LegacyUnit/Fixtures/FrontEnd/TestingView.php
  Tests/LegacyUnit/Fixtures/Model/TitledTestingModel.php
  Tests/LegacyUnit/Fixtures/OldModel/Testing.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingRegistration.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingTimeSpan.php
  Tests/LegacyUnit/Fixtures/Service/TestingSingleViewLinkBuilder.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EMailSalutationTest.php
  Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
Labels: cleanup

#302 [FEATURE] Build with PHP 7.2 on Travis CI
  .travis.yml
  CHANGELOG.md
Labels: enhancement

#304 [BUGFIX] Fix some type errors in the tests
  CHANGELOG.md
  Tests/LegacyUnit/Bag/AbstractTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: bug

#305 [BUGFIX] Update a console parameter name on Travis CI
  .travis.yml
Labels: bug

#306 [BUGFIX] Fix more type errors in the tests
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: bug

#303 [TASK] Use parameter type declarations in the tests
  CHANGELOG.md
  Tests/Functional/Configuration/TypoScriptSetupTest.php
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/RealUrl/ConfigurationTest.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EventListViewTest.php
  Tests/LegacyUnit/Fixtures/BackEnd/TestingEventMailForm.php
  Tests/LegacyUnit/Fixtures/Bag/Testing.php
  Tests/LegacyUnit/Fixtures/BagBuilder/Testing.php
  Tests/LegacyUnit/Fixtures/OldModel/Testing.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingRegistration.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingTimeSlot.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingTimeSpan.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EMailSalutationTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#309 [FEATURE] Refactor registration form footer creation
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
Labels: cleanup

#308 [FEATURE] Enable modifying the BagBuilder limitations for hooks
  CHANGELOG.md
  Classes/BagBuilder/Abstract.php
  Tests/LegacyUnit/BagBuilder/AbstractTest.php
Labels: enhancement

#311 [BUGFIX] Use real records in the FE editor tests
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: bug

#312 [BUGFIX] Fix more type errors
  CHANGELOG.md
  Classes/BagBuilder/Abstract.php
  Classes/BagBuilder/Category.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Model/Event.php
  Classes/OldModel/Abstract.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/BagBuilder/AbstractTest.php
Labels: bug

#314 [BUGFIX] git-ignore the tests-generated var/log/ folder
  .gitignore
  CHANGELOG.md
Labels: bug

#316 [BUGFIX] Stop using removed oelib functionality in the tests
  CHANGELOG.md
  Tests/Functional/Fixtures/BackEndUsers.xml
  Tests/Functional/Mapper/BackEndUserGroupTest.php
  Tests/LegacyUnit/Mapper/BackEndUserGroupTest.php
Labels: bug

#315 [BUGFIX] Fix code inspection warnings
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/AbstractModule.php
  Classes/BackEnd/Controller.php
  Classes/BackEnd/EventsList.php
  Classes/Csv/CsvDownloader.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/FrontEnd/CategoryList.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/Mapper/Event.php
  Classes/Model/Checkbox.php
  Classes/Model/Event.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Place.php
  Classes/Model/Registration.php
  Classes/Model/Speaker.php
  Classes/Model/TargetGroup.php
  Classes/Model/TimeSlot.php
  Classes/OldModel/Abstract.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/OldModel/TimeSlot.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/MailNotifierConfiguration.php
  Classes/Service/EmailService.php
  Classes/Service/EventStatusService.php
  Classes/Service/RegistrationManager.php
  Classes/Service/SingleViewLinkBuilder.php
  Classes/ViewHelper/TimeRange.php
  Tests/Functional/Model/SpeakerTest.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
  composer.json
Labels: bug, cleanup

#321 [CLEANUP] Use the new class name for mocks
  CHANGELOG.md
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php
  Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/EventTopicTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierConfigurationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EventStateServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
Labels: bug, cleanup

#322 [FEATURE] Make installable in TYPO3 9LTS
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: enhancement

#323 [CLEANUP] Wrap accesses to global variables
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/EventsList.php
  Classes/BackEnd/RegistrationsList.php
  Classes/BackEnd/SpeakersList.php
  Classes/ConfigCheck.php
  Classes/Csv/AbstractListView.php
  Classes/Csv/CsvDownloader.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/OldModel/Abstract.php
  Classes/Service/SingleViewLinkBuilder.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/GeneralEventMailFormTest.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EventListViewTest.php
  Tests/LegacyUnit/Fixtures/BackEnd/TestingEventMailForm.php
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EditorTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/EventHeadlineTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
  Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
  Tests/LegacyUnit/FrontEnd/TestingViewTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/TimespanTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
Labels: cleanup

#325 [BUGFIX] Move the plugin registration to Configuration/TCA/Overrides/
  CHANGELOG.md
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TCA/Overrides/tt_content.php
  ext_localconf.php
  ext_tables.php
Labels: bug

#327 [CLEANUP] Streamline ext_localconf.php and ext_tables.php
  CHANGELOG.md
  ext_localconf.php
  ext_tables.php
Labels: cleanup

#329 [CLEANUP] Namespace and rename some legacy test cases
  CHANGELOG.md
  Tests/LegacyUnit/Bag/AbstractBagTest.php
  Tests/LegacyUnit/BagBuilder/AbstractBagBuilderTest.php
  Tests/LegacyUnit/OldModel/AbstractModelTest.php
Labels: cleanup

#331 [CLEANUP] Rename and namespace the old abstract model class
  Classes/Bag/Abstract.php
  Classes/Csv/CsvDownloader.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/Category.php
  Classes/OldModel/Event.php
  Classes/OldModel/Organizer.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingModel.php
Labels: cleanup

#332 [TASK] Rename and namespace the abstract bag class
  Classes/Bag/AbstractBag.php
  Classes/Bag/Category.php
  Classes/Bag/Event.php
  Classes/Bag/Organizer.php
  Classes/Bag/Registration.php
  Classes/Bag/Speaker.php
  Classes/Bag/TimeSlot.php
  Classes/BagBuilder/Abstract.php
  Classes/FrontEnd/DefaultController.php
  Tests/LegacyUnit/BagBuilder/AbstractBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/CategoryTest.php
  Tests/LegacyUnit/BagBuilder/EventTest.php
  Tests/LegacyUnit/BagBuilder/OrganizerTest.php
  Tests/LegacyUnit/BagBuilder/SpeakerTest.php
  Tests/LegacyUnit/Fixtures/Bag/TestingBag.php
Labels: cleanup

#328 [CLEANUP] Rename and namespace the abstract bag builder
  Classes/BagBuilder/AbstractBagBuilder.php
  Classes/BagBuilder/Category.php
  Classes/BagBuilder/Event.php
  Classes/BagBuilder/Organizer.php
  Classes/BagBuilder/Registration.php
  Classes/BagBuilder/Speaker.php
  Tests/LegacyUnit/Fixtures/BagBuilder/BrokenBagBuilder.php
  Tests/LegacyUnit/Fixtures/BagBuilder/TestingBagBuilder.php
Labels: cleanup

#313 [FEATURE] Add hook base
  CHANGELOG.md
  Classes/Hooks/HookProvider.php
  Classes/Hooks/Interfaces/Hook.php
  Tests/Unit/Fixtures/Hooks/TestingHookImplementor.php
  Tests/Unit/Fixtures/Hooks/TestingHookImplementor2.php
  Tests/Unit/Fixtures/Hooks/TestingHookImplementorNotImplementsInterface.php
  Tests/Unit/Fixtures/Hooks/TestingHookInterface.php
  Tests/Unit/Fixtures/Hooks/TestingHookInterfaceNotExtendsHook.php
  Tests/Unit/Hooks/HookProviderTest.php
Labels: enhancement

#334 [BUGFIX] Fix type errors in the tests
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
Labels: bug

#335 [TASK] Avoid using eval in the tests
  CHANGELOG.md
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/Fixtures/TestingDefaultController.php
  Tests/LegacyUnit/Service/Fixtures/TestingRegistrationManager.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#336 [CLEANUP] Move the fixture classes around
  CHANGELOG.md
  Tests/Unit/Hooks/Fixtures/TestingHookImplementor.php
  Tests/Unit/Hooks/Fixtures/TestingHookImplementor2.php
  Tests/Unit/Hooks/Fixtures/TestingHookImplementorNotImplementsInterface.php
  Tests/Unit/Hooks/Fixtures/TestingHookInterface.php
  Tests/Unit/Hooks/Fixtures/TestingHookInterfaceNotExtendsHook.php
  Tests/Unit/Hooks/HookProviderTest.php
Labels: cleanup

#338 [FEATURE] Add new seminar single view hook
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/Hooks/Interfaces/SeminarSingleView.php
  Classes/Interface/Hook/EventSingleView.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: enhancement

#345 [CLEANUP] Remove a redundant import
  CHANGELOG.md
  Classes/Hooks/Interfaces/SeminarSingleView.php
Labels: cleanup

#346 [FEATURE] Add OldModel::fromData
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Tests/Unit/OldModel/AbstractModelTest.php
  Tests/Unit/OldModel/AbstractTimeSpanTest.php
  Tests/Unit/OldModel/CategoryTest.php
  Tests/Unit/OldModel/EventTest.php
  Tests/Unit/OldModel/OrganizerTest.php
  Tests/Unit/OldModel/RegistrationTest.php
  Tests/Unit/OldModel/SpeakerTest.php
  Tests/Unit/OldModel/TimeSlotTest.php
Labels: enhancement

#348 [BUGFIX] Fix code inspection warnings
  CHANGELOG.md
  Classes/Bag/AbstractBag.php
  Classes/Bag/Event.php
  Classes/OldModel/Registration.php
  Tests/LegacyUnit/Fixtures/Bag/TestingBag.php
  Tests/Unit/Hooks/HookProviderTest.php
  Tests/Unit/OldModel/AbstractModelTest.php
Labels: bug, cleanup

#350 [CLEANUP] Remove overloading constructors from testing models
  CHANGELOG.md
  Classes/Bag/Registration.php
  Classes/FrontEnd/DefaultController.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingRegistration.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingTimeSpan.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/TimespanTest.php
  Tests/LegacyUnit/Service/EMailSalutationTest.php
Labels: cleanup

#351 [FEATURE] Add php-cs-fixer to the CI
  .travis.yml
  CHANGELOG.md
  composer.json
Labels: enhancement

#352 [CLEANUP] Fix code inspection warnings
  CHANGELOG.md
  Classes/Bag/Event.php
  Classes/OldModel/Event.php
Labels: cleanup

#353 [BUGFIX] Allow access to non-persisted model data
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/Unit/OldModel/AbstractModelTest.php
Labels: bug

#354 [TASK] Simplify the Bag constructors
  CHANGELOG.md
  Classes/Bag/AbstractBag.php
  Classes/Bag/Category.php
  Classes/Bag/Event.php
  Classes/Bag/Organizer.php
  Classes/Bag/Registration.php
  Classes/Bag/Speaker.php
  Classes/Bag/TimeSlot.php
  Tests/LegacyUnit/Fixtures/Bag/TestingBag.php
Labels: cleanup

#356 [TASK] Move the AbstractModel constructor to the top of the class
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
Labels: cleanup

#360 [BUGFIX] Use the correct prefixes for request parameters
  CHANGELOG.md
  Classes/Csv/CsvDownloader.php
  Classes/FrontEnd/DefaultController.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/Service/RegistrationManager.php
Labels: bug

#364 [FEATURE] Add and use AbstractModel::comesFromDatabase
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/RegistrationsList.php
  Classes/Bag/AbstractBag.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/Hooks/DataHandlerHook.php
  Classes/OldModel/AbstractModel.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/Functional/OldModel/SpeakerTest.php
  Tests/LegacyUnit/OldModel/AbstractModelTest.php
  Tests/LegacyUnit/OldModel/CategoryTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/Unit/OldModel/AbstractModelTest.php
Labels: enhancement

#366 [BUGFIX] Fix the numbers in the countdown tests
  CHANGELOG.md
  Classes/ViewHelper/Countdown.php
  Tests/LegacyUnit/ViewHelper/CountdownTest.php
Labels: bug

#365 [BUGFIX] Fix the numbers in the countdown tests
  CHANGELOG.md
  Classes/ViewHelper/Countdown.php
  Tests/LegacyUnit/ViewHelper/CountdownTest.php
Labels: bug

#367 [BUGFIX] Fix the locallang path in the event publication
  CHANGELOG.md
  Classes/FrontEnd/PublishEvent.php
  Classes/Mapper/Event.php
Labels: bug

#368 [BUGFIX] Fix the locallang path in the event publication
  CHANGELOG.md
  Classes/FrontEnd/PublishEvent.php
  Classes/Mapper/Event.php
Labels: bug

#370 [BUGFIX] Fix the locallang path in the event publication
  CHANGELOG.md
  Classes/FrontEnd/PublishEvent.php
Labels: bug

#369 [TASK] Clean up the translation handling in the tests
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/PublishEventTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/OldModel/TimeSlotTest.php
  Tests/LegacyUnit/OldModel/TimespanTest.php
  Tests/LegacyUnit/Service/EMailSalutationTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/ViewHelper/CountdownTest.php
  Tests/LegacyUnit/ViewHelper/DateRangeTest.php
  Tests/LegacyUnit/ViewHelper/TimeRangeTest.php
  Tests/Unit/Traits/LanguageHelper.php
Labels: cleanup

#371 [CLEANUP] Fix TypoScript lint warnings
  CHANGELOG.md
  Configuration/TypoScript/Forms/EventEditor.txt
  Configuration/TypoScript/Forms/RegistrationStep2.txt
Labels: cleanup

#10 [TASK] Lint the TypoScript
  .travis.yml
  CHANGELOG.md
  Configuration/TsLint.yml
  composer.json
Labels: enhancement

#372 [TASK] Convert model creation by UID to the ConnectionPool
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/LegacyUnit/OldModel/AbstractModelTest.php
Labels: bug

#373 [TASK] Create Speaker.getSkillsShort the ConnectionPool
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/Speaker.php
Labels: bug

#374 [CLEANUP] Reduce code duplication in the bag classes
  CHANGELOG.md
  Classes/Bag/AbstractBag.php
  Classes/Bag/Category.php
  Classes/Bag/Event.php
  Classes/Bag/Organizer.php
  Classes/Bag/Registration.php
  Classes/Bag/Speaker.php
  Classes/Bag/TimeSlot.php
  Tests/LegacyUnit/Fixtures/Bag/TestingBag.php
Labels: cleanup

#375 [TASK] Streamline the functional tests
  CHANGELOG.md
  Tests/Functional/Configuration/TypoScriptSetupTest.php
  Tests/Functional/Fixtures/FrontEndUsers.xml
  Tests/Functional/Fixtures/Registrations.xml
  Tests/Functional/Fixtures/Speakers.xml
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/Hooks/DataHandlerHookTest.php
  Tests/Functional/Mapper/BackEndUserGroupTest.php
  Tests/Functional/Mapper/RegistrationTest.php
  Tests/Functional/Model/SpeakerTest.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/Functional/OldModel/SpeakerTest.php
  Tests/Functional/RealUrl/ConfigurationTest.php
  Tests/Functional/SchedulerTask/RegistrationDigestTest.php
  Tests/Unit/SchedulerTask/RegistrationDigestTest.php
Labels: cleanup

#379 [TASK] Convert AbstractModel::saveToDatabase to the ConnectionPool
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/LegacyUnit/OldModel/AbstractModelTest.php
Labels: bug

#380 [CLEANUP] Drop an unused testing class
  CHANGELOG.md
  Tests/LegacyUnit/Fixtures/OldModel/TestingTimeSpan.php
Labels: cleanup

#383 [TASK] Remove the unused AbstractModeL::retrieveRecord
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
Labels: cleanup

#386 [BUGFIX] Internally store boolean properties as integers
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
Labels: bug

#389 [BUGFIX] Move fragile back-end tests to the new testing framework
  CHANGELOG.md
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/BackEnd/EventsListTest.php
  Tests/Functional/BackEnd/Fixtures/Records.xml
  Tests/Functional/BackEnd/Fixtures/TestingEventMailForm.php
  Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/GeneralEventMailFormTest.php
Labels: bug, cleanup

#390 [TASK] Make the fixture datasets per-namespace
  CHANGELOG.md
  Tests/Functional/Fixtures/Registrations.xml
  Tests/Functional/Mapper/BackEndUserGroupTest.php
  Tests/Functional/Mapper/Fixtures/BackEndUsers.xml
  Tests/Functional/Mapper/Fixtures/Registrations.xml
  Tests/Functional/Mapper/RegistrationTest.php
  Tests/Functional/Model/Fixtures/Speakers.xml
  Tests/Functional/Model/SpeakerTest.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/Functional/OldModel/Fixtures/Speakers.xml
  Tests/Functional/OldModel/Fixtures/Test.xml
  Tests/Functional/OldModel/SpeakerTest.php
Labels: cleanup

#391 [TASK] Move a fragile CSV download test to the new TF
  CHANGELOG.md
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
Labels: bug

#392 [TASK] Convert some fragile bag builder tests to the new TF
  CHANGELOG.md
  Tests/Functional/BagBuilder/EventBagBuilderTest.php
  Tests/Functional/BagBuilder/Fixtures/Records.xml
  Tests/LegacyUnit/BagBuilder/EventTest.php
Labels: bug

#394 [CLEANUP] Code cleanup in the bag builders
  Classes/BagBuilder/AbstractBagBuilder.php
  Classes/BagBuilder/Category.php
  Classes/BagBuilder/Event.php
  Classes/BagBuilder/Organizer.php
  Classes/BagBuilder/Registration.php
  Classes/FrontEnd/DefaultController.php
  Tests/LegacyUnit/BagBuilder/EventTest.php
Labels: cleanup

#393 [BUGFIX] Convert the bag class to the ConnectionPool
  CHANGELOG.md
  Classes/Bag/AbstractBag.php
  Classes/OldModel/Event.php
Labels: bug, cleanup

#395 [CLEANUP] Some testcase cleanup
  Tests/LegacyUnit/OldModel/AbstractModelTest.php
  Tests/LegacyUnit/OldModel/CategoryTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/OrganizerTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/OldModel/TimeSlotTest.php
  Tests/LegacyUnit/Service/EMailSalutationTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/EventStateServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/LegacyUnit/ViewHelper/DateRangeTest.php
  Tests/LegacyUnit/ViewHelper/TimeRangeTest.php
Labels: cleanup

#396 [BUGFIX] Port fragile old model event tests to the new TF
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/Functional/OldModel/EventTest.php
  Tests/Functional/OldModel/Fixtures/Events.xml
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/Unit/OldModel/EventTest.php
Labels: bug, cleanup

#397 [BUGFIX] Convert some DB accesses in the Event model to ConnectionPool
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/Event.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/OldModel/EventTest.php
Labels: bug

#398 [BUGFIX] Replace TYPO3_DB->cleanIntArray
  CHANGELOG.md
  Classes/BagBuilder/Event.php
Labels: bug

#400 [BUGFIX] Replace admin_get_fields
  CHANGELOG.md
  Classes/FlexForms.php
Labels: bug

#401 [BUGFIX] Convert the TceForms to the ConnectionPool
  CHANGELOG.md
  Classes/BackEnd/TceForms.php
Labels: bug

#402 [BUGFIX] Convert the time slot model to the ConnectionPool
  CHANGELOG.md
  Classes/OldModel/TimeSlot.php
  Tests/LegacyUnit/OldModel/TimeSlotTest.php
Labels: bug

#403 [BUGFIX] Convert the registration model to the ConnectionPool
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
Labels: bug

#404 [BUGFIX] Partially convert the event model to the ConnectionPool
  CHANGELOG.md
  Classes/FrontEnd/RegistrationForm.php
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
Labels: bug
