Repository oliverklee/ext-seminars, pull requests merged in 2019-12, with the labels that each got.

#405 [TASK] Drop the unused Event::getRelatedMmRecordUids
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: cleanup

#407 [BUGFIX] Convert the rest of the registration model to the Connection…
  CHANGELOG.md
  Classes/OldModel/Registration.php
Labels: bug

#406 [BUGFIX] Convert the rest of the event model to the ConnectionPool
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/Event.php
Labels: bug

#410 [BUGFIX] Stop using the deprecated NullTimeTracker
  CHANGELOG.md
  Classes/Service/SingleViewLinkBuilder.php
Labels: bug

#411 [CLEANUP] Rename the mapper tests
  Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
  Tests/Functional/Mapper/RegistrationMapperTest.php
Labels: cleanup

#412 [BUGFIX] Fix a failing EventMapper test in 9.5
  CHANGELOG.md
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/Functional/Mapper/Fixtures/Events.xml
  Tests/LegacyUnit/Mapper/EventTest.php
Labels: bug

#413 [BUGFIX] Fix failing speaker bag tests in 9.5
  CHANGELOG.md
  Tests/Functional/Bag/Fixtures/Speakers.xml
  Tests/Functional/Bag/SpeakerBagTest.php
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Bag/SpeakerTest.php
Labels: bug

#414 [BUGFIX] Fix failing bag builder tests in 9.5
  CHANGELOG.md
  Tests/Functional/Bag/SpeakerBagTest.php
  Tests/Functional/BagBuilder/AbstractBagBuilderTest.php
  Tests/Functional/BagBuilder/EventBagBuilderTest.php
  Tests/Functional/BagBuilder/Fixtures/Events.xml
  Tests/Functional/BagBuilder/Fixtures/Testing.xml
  Tests/Functional/Traits/BagHelper.php
  Tests/LegacyUnit/BagBuilder/AbstractBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/EventTest.php
Labels: bug

#415 [BUGFIX] Fix failing CSV downloader tests in 9.5
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/Functional/Csv/Fixtures/EventsAndRegistrations.xml
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
Labels: bug

#417 [CLEANUP] Improve variable names in the BE module
  Classes/BackEnd/AbstractList.php
Labels: cleanup

#418 [BUGFIX] Replace the deprecated editOnClick
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
Labels: bug, cleanup

#419 [CLEANUP] Always use arrays for route generation URL parameters
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/EventsList.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/OrganizersListTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BackEnd/SpeakersListTest.php
Labels: cleanup

#420 [BUGFIX] Stop using BackendUtility::getModuleUrl
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/EventsList.php
Labels: bug

#421 [CLEANUP] Stop pretty-printing the HTML in the BE module
  Classes/BackEnd/AbstractList.php
Labels: cleanup

#422 [CLEANUP] Use more type declarations in the BE module classes
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/CancelEventMailForm.php
  Classes/BackEnd/ConfirmEventMailForm.php
  Classes/BackEnd/Controller.php
  Classes/BackEnd/EventsList.php
  Classes/BackEnd/GeneralEventMailForm.php
  Classes/BackEnd/OrganizersList.php
  Classes/BackEnd/RegistrationsList.php
  Classes/BackEnd/SpeakersList.php
  Tests/LegacyUnit/BackEnd/Fixtures/DummyModule.php
Labels: cleanup

#423 [BUGFIX] Replace the removed getTabMenu
  CHANGELOG.md
  Classes/BackEnd/Controller.php
Labels: bug

#424 [BUGFIX] Use propert routes in the BE tab menu
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/Controller.php
Labels: bug

#425 [BUGFIX] Stop using getLinkToDataHandlerAction
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
Labels: bug

#426 [BUGFIX] Stop using getModuleUrl in the functional tests
  CHANGELOG.md
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
Labels: bug

#408 [FEATURE] Add seminar list view hooks
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/Hooks/Interfaces/SeminarListView.php
  Classes/Interface/Hook/EventListView.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: enhancement

#428 [BUGFIX] Move the event headline test to the new testing framework
  CHANGELOG.md
  Classes/FrontEnd/EventHeadline.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/FrontEnd/Fixtures/EventHeadline.xml
  Tests/LegacyUnit/FrontEnd/EventHeadlineTest.php
Labels: bug

#429 [BUGFIX] Move the dependencies/requirements tests to the new TF
  CHANGELOG.md
  Tests/Functional/Mapper/DateMapperTest.php
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/Functional/Mapper/Fixtures/Dates.xml
  Tests/Functional/Mapper/Fixtures/Topics.xml
  Tests/Functional/Mapper/TopicMapperTest.php
  Tests/Functional/Traits/ListHelper.php
  Tests/LegacyUnit/Mapper/EventDateTest.php
  Tests/LegacyUnit/Mapper/EventTopicTest.php
  Tests/LegacyUnit/Mapper/SingleEventTest.php
Labels: bug

#430 [TASK] Require oelib >= 3.0.3
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: bug

#434 [CLEANUP] Sort the entries in .gitignore/.gitattributes
  .gitattributes
  .gitignore
  CHANGELOG.md
Labels: cleanup

#432 [FEATURE] Add composer command to render the documentation using docker-compose
  .gitattributes
  .gitignore
  CHANGELOG.md
  composer.json
  docker-compose.yml
Labels: enhancement

#436 [FEATURE] Add selector widget hook, test and docs
  CHANGELOG.md
  Classes/FrontEnd/SelectorWidget.php
  Classes/Hooks/Interfaces/SeminarSelectorWidget.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
Labels: enhancement

#438 [BUGFIX] Fix event editor tests in 9.5 on Travis CI
  CHANGELOG.md
  Classes/FrontEnd/EventEditor.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  Tests/Functional/FrontEnd/Fixtures/EventEditorTest.xml
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
Labels: bug

#439 [TASK] Convert MailNotifierConfigurationTest to the new TF
  CHANGELOG.md
  Classes/SchedulerTasks/MailNotifierConfiguration.php
  Tests/Functional/SchedulerTask/Fixtures/MailNotifierConfiguration.xml
  Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
  Tests/Unit/SchedulerTask/MailNotifierConfigurationTest.php
Labels: cleanup

#440 [BUGFIX] Fix the scheduler task flash messages in 9.5
  CHANGELOG.md
  Classes/SchedulerTasks/MailNotifierConfiguration.php
  Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
Labels: bug

#441 [CLEANUP] Break overlong lines in the default controller test
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: cleanup

#442 [BUGFIX] Convert some default controller tests to the new TF
  CHANGELOG.md
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/FrontEnd/Fixtures/EventList.xml
  Tests/Functional/FrontEnd/Fixtures/EventListWithCategories.xml
  Tests/Functional/FrontEnd/Fixtures/EventListWithPlaces.xml
  Tests/Functional/FrontEnd/Fixtures/EventListWithTypes.xml
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: bug

#324 [FEATURE] Add a TYPO3 9.5 build to Travis CI
  .travis.yml
  CHANGELOG.md
  composer.json
Labels: enhancement
