Repository oliverklee/ext-seminars, pull requests merged in 2019-07, with the labels that each got.

#217 [TASK] Pass user object in modifySalutation hook
  CHANGELOG.md
  Classes/EmailSalutation.php
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/LegacyUnit/Service/EMailSalutationTest.php
Labels: enhancement

#218 [FEATURE] Add Speaker.image
  CHANGELOG.md
  Classes/Model/Speaker.php
  Classes/OldModel/Speaker.php
  Configuration/TCA/tx_seminars_speakers.php
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang_db.xlf
  Tests/Functional/Fixtures/Speakers.xml
  Tests/Functional/Model/SpeakerTest.php
  Tests/Functional/OldModel/SpeakerTest.php
  Tests/Functional/Traits/FalHelper.php
  Tests/Unit/Model/SpeakerTest.php
  ext_tables.sql
Labels: enhancement

#220 [FEATURE] Display the speaker image in the event single view
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/OldModel/Event.php
  Configuration/TypoScript/FrontEnd.txt
  Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
  Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
  Resources/Private/Language/FrontEnd/de.locallang.xlf
  Resources/Private/Language/FrontEnd/locallang.xlf
  Resources/Private/Templates/FrontEnd/FrontEnd.html
Labels: enhancement

#222 [TASK] Remove deprecated "replaces" entry from composer.json
  CHANGELOG.md
  composer.json
Labels: bug, cleanup

#223 [BUGFIX] Fix the build on Travis CI
  .travis.yml
  CHANGELOG.md
Labels: bug

#225 [BUGFIX] Fix the CSV export label in the BE module in TYPO3 8LTS
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/EventsList.php
  Resources/Private/Language/BackEnd/de.locallang.xlf
  Resources/Private/Language/BackEnd/locallang.xlf
Labels: bug
