Repository oliverklee/ext-seminars, pull requests merged in 2020-11, with the labels that each got.

#562 [TASK] Remove redundant code line
  Classes/BackEnd/AbstractList.php
Labels: cleanup

#568 [FEATURE] Add an .editorconfig file
  .editorconfig
  .gitattributes
  CHANGELOG.md
Labels: enhancement

#571 [FEATURE] Add support for PHP 7.3 and 7.4
  .github/workflows/ci.yml
  CHANGELOG.md
  Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
  composer.json
  ext_emconf.php
Labels: enhancement

#573 [CLEANUP] Remove a leftover "fail-fast" from the CI configuration
  .github/workflows/ci.yml
Labels: cleanup

#578 [BUGFIX] Fix a test failure with mocks with PHP 7.4
  CHANGELOG.md
  Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
Labels: bug
