Repository oliverklee/ext-seminars, pull requests merged in 2020-02, with the labels that each got.

#501 Fix typo in DE "known problems" doc
  Documentation/DE/BekannteProbleme/Index.rst
Labels: bug

#500 [TASK] Remove outdated sentence from the installation section in the docs
  Documentation/DE/Installation/DieErweiterungInstallieren/Index.rst
  Documentation/EN/Installation/InstallingTheExtension/Index.rst
Labels: documentation

#502 [TASK] Improve the code autoformatting
  CHANGELOG.md
  Configuration/TCA/Overrides/fe_users.php
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TCA/tx_seminars_attendances.php
  Configuration/TCA/tx_seminars_categories.php
  Configuration/TCA/tx_seminars_checkboxes.php
  Configuration/TCA/tx_seminars_event_types.php
  Configuration/TCA/tx_seminars_foods.php
  Configuration/TCA/tx_seminars_lodgings.php
  Configuration/TCA/tx_seminars_organizers.php
  Configuration/TCA/tx_seminars_payment_methods.php
  Configuration/TCA/tx_seminars_seminars.php
  Configuration/TCA/tx_seminars_sites.php
  Configuration/TCA/tx_seminars_skills.php
  Configuration/TCA/tx_seminars_speakers.php
  Configuration/TCA/tx_seminars_target_groups.php
  Configuration/TCA/tx_seminars_test.php
  Configuration/TCA/tx_seminars_timeslots.php
  Configuration/php-cs-fixer.php
  composer.json
Labels: bug, enhancement

#504 [TASK] Add more live examples to the manual
  CHANGELOG.md
  Documentation/EN/Introduction/LiveExamples.rst
Labels: documentation

#506 [CLEANUP] Change the casing of Registration::setFrontEndUserUID
  CHANGELOG.md
  Classes/OldModel/Registration.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
Labels: cleanup

#508 [FEATURE] Add Registration::setFrontEndUser() and cache it
  CHANGELOG.md
  Classes/OldModel/Registration.php
  Classes/Service/RegistrationManager.php
  Tests/Unit/OldModel/RegistrationTest.php
Labels: cleanup, enhancement

#509 [TASK] Move some registration tests to the new TF
  CHANGELOG.md
  Classes/OldModel/Registration.php
  Tests/Functional/OldModel/RegistrationTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
Labels: cleanup

#510 [CLEANUP] Merge the testing registration model into the regular model
  CHANGELOG.md
  Classes/OldModel/Registration.php
  Tests/Functional/OldModel/RegistrationTest.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingRegistration.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/OldModel/RegistrationTest.php
Labels: cleanup
