Repository oliverklee/ext-seminars, pull requests merged in 2020-01, with the labels that each got.

#447 [BUGFIX] Fix PHP syntax errors in the documentation
  CHANGELOG.md
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
Labels: bug

#448 [BUGFIX] Fix image references in the documentation
  CHANGELOG.md
  Documentation/DE/Benutzerhandbuch/DasBack-end-modulVeranstaltungen/Images.txt
  Documentation/EN/UsersManual/TheBack-endModuleEvents/Images.txt
  Documentation/Images/csv.gif
Labels: bug

#444 [FEATURE] Enhance hook provider
  CHANGELOG.md
  Classes/Hooks/HookProvider.php
  Tests/Unit/Hooks/Fixtures/TestingHookImplementorReturnsArray.php
  Tests/Unit/Hooks/Fixtures/TestingHookImplementorReturnsArray2.php
  Tests/Unit/Hooks/Fixtures/TestingHookInterfaceReturnsArray.php
  Tests/Unit/Hooks/HookProviderTest.php
Labels: enhancement

#452 [BUGFIX] Fix a test case namespace
  CHANGELOG.md
  Tests/Unit/Model/SkillTest.php
Labels: bug

#445 [FEATURE] Enhance email registration hook in RegistrationManager
  CHANGELOG.md
  Classes/Hooks/Interfaces/RegistrationEmail.php
  Classes/Hooks/RegistrationEmailHookInterface.php
  Classes/Service/RegistrationManager.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: enhancement

#458 [CLEANUP] Convert new hooks to new models
  Classes/BackEnd/RegistrationsList.php
  Classes/Hooks/Interfaces/BackendRegistrationListView.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
Labels: cleanup

#459 [FEATURE] Enhance hook provider with methods passing on the modified value
  CHANGELOG.md
  Classes/Hooks/HookProvider.php
  Tests/Unit/Hooks/Fixtures/TestingHookImplementorReturnsModifiedValue.php
  Tests/Unit/Hooks/Fixtures/TestingHookImplementorReturnsModifiedValue2.php
  Tests/Unit/Hooks/Fixtures/TestingHookInterfaceReturnsModifiedValue.php
  Tests/Unit/Hooks/HookProviderTest.php
Labels: enhancement

#461 [BUGFIX] Fix a MySQL strict error when getting the cities for an event
  CHANGELOG.md
  Classes/OldModel/Event.php
Labels: bug

#462 [BUGFIX] Fix the event begin/end date calculation by timeslots
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/Functional/Hooks/DataHandlerHookTest.php
  Tests/Functional/Hooks/Fixtures/DataMapperHook/TimeSlots.xml
Labels: bug

#466 [BUGFIX] Stop using code that was deprecated in TYPO3 8.7
  CHANGELOG.md
  Classes/FrontEnd/RegistrationForm.php
Labels: bug

#467 [BUGFIX] Update the locations of the mkforms JavaScript includes
  CHANGELOG.md
  Configuration/TypoScript/Config.txt
  composer.json
  ext_emconf.php
Labels: bug

#468 [BUGFIX] Update the locations of the mkforms JavaScript includes
  CHANGELOG.md
  Configuration/TypoScript/Config.txt
  composer.json
  ext_emconf.php
Labels: bug

#472 [CLEANUP] Clean up the DataHandler hooks
  Classes/Hooks/DataHandlerHook.php
  Classes/OldModel/Event.php
Labels: cleanup

#473 [CLEANUP] Refactor the data handler tests
  Classes/Hooks/DataHandlerHook.php
  Tests/Functional/Hooks/DataHandlerHookTest.php
Labels: cleanup

#474 [TASK] Simplify the data handler hooks
  Classes/Hooks/DataHandlerHook.php
  Tests/Functional/Hooks/DataHandlerHookTest.php
Labels: cleanup

#475 [CLEANUP] Code clean up in the old registration model
  Classes/OldModel/Registration.php
Labels: cleanup

#476 [CLEANUP] Code clean up in the old registration model
  Classes/OldModel/Registration.php
Labels: cleanup

#477 [BUGFIX] Fix type error with dates in the old registration model
  CHANGELOG.md
  Classes/OldModel/Registration.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
Labels: bug

#478 [BUGFIX] Fix type error with dates in the old registration model
  CHANGELOG.md
  Classes/OldModel/Registration.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
Labels: bug

#479 [BUGFIX] Add the missing label for the date of birth for emails
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
Labels: bug

#480 [BUGFIX] Add the missing label for the date of birth for emails
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
Labels: bug

#481 [BUGFIX] Avoid double colons for labels in organizer notification emails
  CHANGELOG.md
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
Labels: bug

#482 [BUGFIX] Avoid double colons for labels in organizer notification email
  CHANGELOG.md
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
Labels: bug

#483 [TASK] Move the data handling sanitization from old model to hook
  CHANGELOG.md
  Classes/Hooks/DataHandlerHook.php
  Classes/OldModel/Event.php
Labels: cleanup

#484 [TASK] Move getting begin/end dates from timeslots to the hook
  CHANGELOG.md
  Classes/Hooks/DataHandlerHook.php
  Classes/OldModel/Event.php
Labels: cleanup

#486 [TASK] Move copying the places from time slots to the data handler hook
  CHANGELOG.md
  Classes/Hooks/DataHandlerHook.php
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/Event.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: cleanup

#490 [BUGFIX] Fix the rendering markup for locations
  CHANGELOG.md
  Classes/OldModel/Event.php
  Configuration/TCA/tx_seminars_sites.php
  Configuration/TCA/tx_seminars_timeslots.php
Labels: bug

#491 [BUGFIX] Fix the rendering markup for locations
  CHANGELOG.md
  Classes/OldModel/Event.php
  Configuration/TCA/tx_seminars_sites.php
  Configuration/TCA/tx_seminars_timeslots.php
Labels: bug

#492 [BUGFIX] Remove colons from the end of TCEforms labels
  CHANGELOG.md
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/dk.locallang_db.xlf
  Resources/Private/Language/fr.locallang_db.xlf
  Resources/Private/Language/it.locallang_db.xlf
  Resources/Private/Language/locallang_db.xlf
  Resources/Private/Language/nl.locallang_db.xlf
  Resources/Private/Language/ru.locallang_db.xlf
Labels: bug

#493 [BUGFIX] Fix an incorrect type annotation
  CHANGELOG.md
  Classes/Hooks/DataHandlerHook.php
Labels: bug

#495 [CLEANUP] Code formatting cleanup
  Classes/FrontEnd/DefaultController.php
  Classes/OldModel/Event.php
Labels: cleanup
