Repository oliverklee/ext-seminars, pull requests merged in 2020-12, with the labels that each got.

#598 [BUGFIX] Stop converting class names to PSR-4
  CHANGELOG.md
  Configuration/php-cs-fixer.php
Labels: bug

#601 [CLEANUP] Add more type declarations in the tests
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: cleanup

#602 [CLEANUP] Use oelib's Typo3Version class for version checks
  Classes/FrontEnd/RegistrationForm.php
Labels: bug, cleanup

#603 [CLEANUP] Stop using $this->getFrontEndController()->tmpl->getFileName()
  Classes/ConfigCheck.php
Labels: bug, cleanup

#596 [TASK] Add more type declarations
  Classes/BagBuilder/Category.php
  Classes/BagBuilder/Event.php
  Classes/Csv/AbstractBackEndAccessCheck.php
  Classes/Csv/AbstractListView.php
  Classes/Csv/AbstractRegistrationListView.php
  Classes/Csv/BackEndEventAccessCheck.php
  Classes/Csv/BackEndRegistrationAccessCheck.php
  Classes/Csv/CsvDownloader.php
  Classes/Csv/DownloadRegistrationListView.php
  Classes/Csv/EmailRegistrationListView.php
  Classes/Csv/EventListView.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/EmailSalutation.php
  Classes/FrontEnd/AbstractView.php
  Classes/FrontEnd/CategoryList.php
  Classes/FrontEnd/Countdown.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/Editor.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/EventHeadline.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/Interface/CsvAccessCheck.php
  Classes/Interface/Titled.php
  Classes/Mapper/Event.php
  Classes/Model/BackEndUser.php
  Classes/Model/Category.php
  Classes/Model/Checkbox.php
  Classes/Model/Event.php
  Classes/Model/EventType.php
  Classes/Model/Food.php
  Classes/Model/Lodging.php
  Classes/Model/Organizer.php
  Classes/Model/PaymentMethod.php
  Classes/Model/Place.php
  Classes/Model/Registration.php
  Classes/Model/Skill.php
  Classes/Model/Speaker.php
  Classes/Model/TargetGroup.php
  Classes/Model/TimeSlot.php
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/Event.php
  Classes/OldModel/Organizer.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/EmailService.php
  Classes/Service/RegistrationManager.php
  Classes/ViewHelper/DateRange.php
  Classes/ViewHelper/TimeRange.php
  Tests/LegacyUnit/BagBuilder/CategoryBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: cleanup

#624 [CLEANUP] Move FlexForms to Backend\FlexForms
  Classes/BackEnd/FlexForms.php
  Configuration/FlexForms/flexforms_pi1.xml
  Tests/LegacyUnit/BackEnd/FlexFormsTest.php
Labels: cleanup

#627 [CLEANUP] Migrate Tx_Seminars_Interface_Titled to Model namespace
  Classes/FrontEnd/EventEditor.php
  Classes/Model/BackEndUserGroup.php
  Classes/Model/Category.php
  Classes/Model/Checkbox.php
  Classes/Model/Event.php
  Classes/Model/EventType.php
  Classes/Model/Food.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Interfaces/Titled.php
  Classes/Model/Lodging.php
  Classes/Model/Organizer.php
  Classes/Model/PaymentMethod.php
  Classes/Model/Place.php
  Classes/Model/Registration.php
  Classes/Model/Skill.php
  Classes/Model/TargetGroup.php
  Classes/ViewHelper/CommaSeparatedTitles.php
  Tests/LegacyUnit/Fixtures/Model/TitledTestingModel.php
  Tests/Unit/Model/EventTest.php
Labels: cleanup

#626 [CLEANUP] Move Tx_Seminars_Interface_CsvAccessCheck to Csv namespace
  Classes/Csv/AbstractBackEndAccessCheck.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/Csv/Interfaces/CsvAccessCheck.php
  Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php
  Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
Labels: cleanup

#625 [CLEANUP] Move EmailSalutation to Email\Salutation
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/Email/Salutation.php
  Classes/Service/EmailService.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
Labels: cleanup

#628 [CLEANUP] Namespace the CSV classes
  Classes/BackEnd/Controller.php
  Classes/BackEnd/EventsList.php
  Classes/Csv/AbstractBackEndAccessCheck.php
  Classes/Csv/AbstractListView.php
  Classes/Csv/AbstractRegistrationListView.php
  Classes/Csv/BackEndEventAccessCheck.php
  Classes/Csv/BackEndRegistrationAccessCheck.php
  Classes/Csv/CsvDownloader.php
  Classes/Csv/DownloadRegistrationListView.php
  Classes/Csv/EmailRegistrationListView.php
  Classes/Csv/EventListView.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RequirementsList.php
  Classes/Hooks/Interfaces/RegistrationListCsv.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/RegistrationManager.php
  Configuration/TypoScript/CsvExport.txt
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/BackEnd/ControllerTest.php
  Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php
  Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EventListViewTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#630 [CLEANUP] Update \Tx_Oelib_Db calls in the tests
  Tests/LegacyUnit/OldModel/TimeSlotTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#631 [CLEANUP] Switch \Tx_Oelib_Db calls in the RegistrationManager to the new ConnectionPool
  Classes/Service/RegistrationManager.php
Labels: cleanup

#632 [CLEANUP] Switch \Tx_Oelib_Db calls in the scheduler task to the new ConnectionPool
  Classes/SchedulerTasks/MailNotifierConfiguration.php
Labels: cleanup

#636 [CLEANUP] Switch \Tx_Oelib_Db calls in RegistrationForm to the new ConnectionPool
  Classes/OldModel/Registration.php
Labels: cleanup

#633 [CLEANUP] Switch \Tx_Oelib_Db calls in RegistrationForm to the new ConnectionPool
  Classes/FrontEnd/RegistrationForm.php
Labels: cleanup

#638 [CLEANUP] Switch \Tx_Oelib_Db calls in SelectorWidget to the new ConnectionPool
  Classes/FrontEnd/SelectorWidget.php
Labels: cleanup

#640 [CLEANUP] Switch \Tx_Oelib_Db calls in EventMapper to the new ConnectionPool
  Classes/Mapper/Event.php
Labels: cleanup

#641 [CLEANUP] Switch \Tx_Oelib_Db calls in the ConfigCheck to the new ConnectionPool
  Classes/ConfigCheck.php
Labels: cleanup

#639 [CLEANUP] Switch DB calls in OldModel\Event to the new ConnectionPool
  Classes/OldModel/Event.php
Labels: cleanup

#642 [CLEANUP] Remove \Tx_Oelib_Db call in BagBuilder\Registration
  Classes/BagBuilder/AbstractBagBuilder.php
  Classes/BagBuilder/Registration.php
Labels: cleanup

#643 [CLEANUP] Switch \Tx_Oelib_Db calls in the BagBuilder\Event to the new ConnectionPool
  Classes/BagBuilder/AbstractBagBuilder.php
  Classes/BagBuilder/Event.php
Labels: cleanup

#651 [BUGFIX] Stop using event model prophecies in the scheduler task tests
  CHANGELOG.md
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
Labels: bug, cleanup

#644 [CLEANUP] Switch \Tx_Oelib_Db calls in AbstractBag to the new ConnectionPool
  Classes/Bag/AbstractBag.php
Labels: cleanup
