Repository oliverklee/ext-seminars, pull requests merged in 2020-04, with the labels that each got.

#523 [BUGFIX] Remove whitespace around the email salutation
  CHANGELOG.md
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: bug

#525 [BUGFIX] Downgrade to PHPUnit 6.5
  CHANGELOG.md
  composer.json
Labels: bug

#524 [TASK] Move some registration form tests to the new TF
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
Labels: cleanup

#526 [BUGFIX] Stop accessing FrontEndController::loginUser in TYPO3 9
  CHANGELOG.md
  Classes/FrontEnd/RegistrationForm.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
Labels: bug

#528 [BUGFIX] Always use Composer-installed versions of the dev tools
  CHANGELOG.md
  composer.json
Labels: bug

#529 [CLEANUP] Clean up the registration form class a bit
  CHANGELOG.md
  Classes/FrontEnd/RegistrationForm.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
Labels: cleanup

#531 [BUGFIX] Attach the registration checkboxes to dates, not topics
  CHANGELOG.md
  Configuration/TCA/tx_seminars_seminars.php
  Tests/Functional/OldModel/EventTest.php
  Tests/Functional/OldModel/Fixtures/Events/Checkboxes.xml
Labels: bug

#533 [BUGFIX] Check the dates for checkboxes, not the topics
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/Unit/OldModel/EventTest.php
Labels: bug

#535 [BUGFIX] Use proper label tags for the terms checkboxes
  CHANGELOG.md
  Resources/Private/Templates/FrontEnd/RegistrationEditor.html
Labels: bug

#536 [BUGFIX] Fix the alignment of labels with umlauts in the emails
  CHANGELOG.md
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
Labels: bug

#460 [FEATURE] Add time span hooks, tests and docs
  CHANGELOG.md
  Classes/Hooks/Interfaces/DateTimeSpan.php
  Classes/OldModel/AbstractTimeSpan.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/OldModel/AbstractTimeSpanTest.php
Labels: enhancement

#511 [TASK] Use TYPO3 system mail as sender mail due to SPF restrictions
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/FrontEnd/EventEditor.php
  Classes/Model/Event.php
  Classes/Model/Traits/EventEmailSenderTrait.php
  Classes/OldModel/Event.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/EmailService.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/Model/EventTest.php
  Tests/Unit/OldModel/EventTest.php
Labels: bug, enhancement

#537 [BUGFIX] Show user group names in the notification email
  CHANGELOG.md
  Classes/OldModel/Registration.php
  Tests/Functional/OldModel/Fixtures/Registrations/Users.xml
  Tests/Functional/OldModel/RegistrationTest.php
Labels: bug

#539 [TASK] Move tests for Registration::getBillingAddress to the new TF
  CHANGELOG.md
  Tests/Functional/OldModel/RegistrationTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/Unit/OldModel/RegistrationTest.php
Labels: cleanup

#540 [BUGFIX] Include the company in the billing address in the emails
  CHANGELOG.md
  Classes/OldModel/Registration.php
  Tests/Unit/OldModel/RegistrationTest.php
Labels: bug
