Repository oliverklee/ext-seminars, pull requests merged in 2021-01, with the labels that each got.

#652 [CLEANUP] Autoformat some tests
  Tests/Unit/OldModel/EventTest.php
Labels: cleanup

#653 [TASK] Fix and modernize tests for event attachments
  CHANGELOG.md
  Tests/Functional/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/Unit/OldModel/EventTest.php
Labels: bug, cleanup

#654 [CLEANUP] Clean up OldModel\Event::getAttachedFiles
  Classes/OldModel/Event.php
Labels: cleanup

#655 [TASK] Fix and update some category lists to the new testing framework
  CHANGELOG.md
  Tests/Functional/FrontEnd/CategoryListTest.php
  Tests/Functional/FrontEnd/Fixtures/CategoryList/OneCategoryWithAsciiTitle.xml
  Tests/Functional/FrontEnd/Fixtures/CategoryList/OneCategoryWithSpecialCharactersInTitle.xml
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
Labels: bug, cleanup

#658 [CLEANUP] Use the namespaced version of the oelib database service
  CHANGELOG.md
  Classes/Bag/AbstractBag.php
  Classes/BagBuilder/AbstractBagBuilder.php
Labels: cleanup

#661 [CLEANUP] Use the namespace oelib login managers
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Classes/Csv/AbstractBackEndAccessCheck.php
  Classes/Csv/BackEndRegistrationAccessCheck.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RequirementsList.php
  Classes/OldModel/Event.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/OrganizersListTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BackEnd/SpeakersListTest.php
  Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php
  Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#662 [CLEANUP] Use the namespaced oelib model classes
  CHANGELOG.md
  Classes/FrontEnd/EventEditor.php
  Classes/Model/AbstractTimeSpan.php
  Classes/Model/BackEndUser.php
  Classes/Model/BackEndUserGroup.php
  Classes/Model/Category.php
  Classes/Model/Checkbox.php
  Classes/Model/Event.php
  Classes/Model/EventType.php
  Classes/Model/Food.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Lodging.php
  Classes/Model/Organizer.php
  Classes/Model/PaymentMethod.php
  Classes/Model/Place.php
  Classes/Model/Registration.php
  Classes/Model/Skill.php
  Classes/Model/Speaker.php
  Classes/Model/TargetGroup.php
  Classes/OldModel/Event.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/Fixtures/Model/TitledTestingModel.php
  Tests/LegacyUnit/Fixtures/Model/UntitledTestingModel.php
  Tests/LegacyUnit/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/LegacyUnit/Model/FrontEndUserGroupTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/Model/PlaceTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#663 [CLEANUP] Use the namespaced oelib template classes
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Classes/Csv/CsvDownloader.php
  Classes/FrontEnd/AbstractView.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/PublishEvent.php
  Classes/Hooks/Interfaces/BackendRegistrationListView.php
  Classes/Hooks/Interfaces/RegistrationEmail.php
  Classes/Hooks/RegistrationEmailHookInterface.php
  Classes/Interface/Hook/EventListView.php
  Classes/Interface/Hook/EventSingleView.php
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/Event.php
  Classes/OldModel/Speaker.php
  Classes/Service/ConfigurationService.php
  Classes/Service/RegistrationManager.php
  Classes/Service/SingleViewLinkBuilder.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/Fixtures/DummyObjectToCheck.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
Labels: cleanup

#664 [CLEANUP] Use the namespace oelib Collection class
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/Mapper/Event.php
  Classes/Model/AbstractTimeSpan.php
  Classes/Model/Event.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Registration.php
  Classes/Model/Speaker.php
  Classes/OldModel/Event.php
  Classes/SchedulerTasks/RegistrationDigest.php
  Classes/ViewHelper/CommaSeparatedTitles.php
  Tests/Functional/Mapper/DateMapperTest.php
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/Functional/Mapper/TopicMapperTest.php
  Tests/Functional/Traits/CollectionHelper.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/Mapper/EventDateMapperTest.php
  Tests/LegacyUnit/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Mapper/EventTopicMapperTest.php
  Tests/LegacyUnit/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Mapper/SingleEventMapperTest.php
  Tests/LegacyUnit/Mapper/SpeakerMapperTest.php
  Tests/LegacyUnit/Mapper/TimeSlotMapperTest.php
  Tests/LegacyUnit/Model/BackEndUserTest.php
  Tests/LegacyUnit/Model/EventDateTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/EventTopicTest.php
  Tests/LegacyUnit/Model/FrontEndUserGroupTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/Model/SpeakerTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/EventStateServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/ViewHelpers/CommaSeparatedTitlesViewHelperTest.php
  Tests/Unit/Model/EventTest.php
Labels: cleanup

#665 [CLEANUP] Use the namespaced oelib interfaces
  CHANGELOG.md
  Classes/Bag/AbstractBag.php
  Classes/BagBuilder/Event.php
  Classes/FrontEnd/AbstractView.php
  Classes/FrontEnd/DefaultController.php
  Classes/Model/Organizer.php
  Classes/Model/Speaker.php
  Classes/OldModel/Event.php
  Classes/OldModel/Organizer.php
  Classes/OldModel/Registration.php
  Classes/ViewHelper/Countdown.php
  Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/Fixtures/DummyObjectToCheck.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/ViewHelpers/CountdownViewHelperTest.php
  Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php
Labels: cleanup

#666 [CLEANUP] Use the namespaces oelib mapper classes
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/RegistrationsList.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/Mapper/BackEndUser.php
  Classes/Mapper/BackEndUserGroup.php
  Classes/Mapper/Event.php
  Classes/Mapper/FrontEndUser.php
  Classes/Mapper/FrontEndUserGroup.php
  Classes/Mapper/Registration.php
  Classes/Model/Event.php
  Classes/Model/Place.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/RegistrationDigest.php
  Classes/Service/EventStatusService.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  Tests/Functional/SchedulerTask/RegistrationDigestTest.php
  Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/OrganizersListTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BackEnd/SpeakersListTest.php
  Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/Mapper/CheckboxMapperTest.php
  Tests/LegacyUnit/Mapper/EventDateMapperTest.php
  Tests/LegacyUnit/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Mapper/EventTopicMapperTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserMapperTest.php
  Tests/LegacyUnit/Mapper/PlaceMapperTest.php
  Tests/LegacyUnit/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Mapper/SingleEventMapperTest.php
  Tests/LegacyUnit/Mapper/SpeakerMapperTest.php
  Tests/LegacyUnit/Mapper/TargetGroupMapperTest.php
  Tests/LegacyUnit/Mapper/TimeSlotMapperTest.php
  Tests/LegacyUnit/Model/BackEndUserTest.php
  Tests/LegacyUnit/Model/EventDateTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/FrontEndUserGroupTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/Model/PlaceTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/Service/EventStateServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/Unit/OldModel/SpeakerTest.php
  Tests/Unit/SchedulerTask/RegistrationDigestTest.php
Labels: cleanup

#667 [CLEANUP] Use the namespaced oelib configuration classes
  CHANGELOG.md
  Classes/BackEnd/Controller.php
  Classes/Csv/AbstractListView.php
  Classes/Csv/CsvDownloader.php
  Classes/Csv/EventListView.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/Email/Salutation.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Model/Event.php
  Classes/OldModel/Event.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/RegistrationDigest.php
  Classes/Service/RegistrationManager.php
  Classes/Service/SingleViewLinkBuilder.php
  Classes/ViewHelper/DateRange.php
  Classes/ViewHelper/TimeRange.php
  Configuration/TypoScript/Forms/EventEditor.txt
  Configuration/TypoScript/Forms/RegistrationStep1.txt
  Configuration/TypoScript/Forms/RegistrationStep2.txt
  Configuration/TypoScript/Forms/Unregistration.txt
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/SchedulerTask/RegistrationDigestTest.php
  Tests/LegacyUnit/BackEnd/AbstractModuleTest.php
  Tests/LegacyUnit/ConfigCheckTest.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EventListViewTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
  Tests/LegacyUnit/ViewHelpers/DateRangeViewHelperTest.php
  Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php
  Tests/Unit/SchedulerTask/RegistrationDigestTest.php
Labels: cleanup

#668 [CLEANUP] Use the namespaced oelib AbstractDataMapper
  CHANGELOG.md
  Classes/Mapper/Category.php
  Classes/Mapper/Checkbox.php
  Classes/Mapper/Event.php
  Classes/Mapper/EventType.php
  Classes/Mapper/Food.php
  Classes/Mapper/Lodging.php
  Classes/Mapper/Organizer.php
  Classes/Mapper/PaymentMethod.php
  Classes/Mapper/Place.php
  Classes/Mapper/Registration.php
  Classes/Mapper/Skill.php
  Classes/Mapper/Speaker.php
  Classes/Mapper/TargetGroup.php
  Classes/Mapper/TimeSlot.php
Labels: cleanup

#669 [CLEANUP] Use more namespaced oelib classes
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/RegistrationsList.php
  Classes/ConfigCheck.php
  Classes/Csv/CsvDownloader.php
  Classes/Email/Salutation.php
  Classes/FrontEnd/Countdown.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/Mapper/Event.php
  Classes/Model/Place.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/Registration.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/RegistrationManager.php
  Classes/ViewHelper/Countdown.php
  Classes/ViewHelper/DateRange.php
  Classes/ViewHelper/TimeRange.php
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/EventsListTest.php
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/GeneralEventMailFormTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
  Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
Labels: cleanup

#670 [CLEANUP] Use the namespaced oelib email-related classes
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/CancelEventMailForm.php
  Classes/BackEnd/ConfirmEventMailForm.php
  Classes/BackEnd/GeneralEventMailForm.php
  Classes/FrontEnd/EventEditor.php
  Classes/Hooks/Interfaces/RegistrationEmail.php
  Classes/Hooks/RegistrationEmailHookInterface.php
  Classes/Interface/Hook/BackEndModule.php
  Classes/Model/Traits/EventEmailSenderTrait.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/EmailService.php
  Classes/Service/RegistrationManager.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#671 [CLEANUP] Convert the remaning usages of non-namespaced oelib classes
  CHANGELOG.md
  Classes/OldModel/Event.php
  Classes/Service/RegistrationManager.php
Labels: cleanup

#678 [BUGFIX] Raise limit of field endtime to 2038-1-1
  Configuration/TCA/tx_seminars_seminars.php
Labels: bug

#681 [BUGFIX] Also run the CI build for PRs against maintenance branches
  .github/workflows/ci.yml
Labels: bug

#682 [BUGFIX] Drop some outdated tests
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: bug

#680 [BUGFIX] Add a missing return type declaration
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
Labels: bug

#683 [FEATURE] Add traits for testing email and makeInstance instances
  CHANGELOG.md
  Tests/Unit/Traits/EmailTrait.php
  Tests/Unit/Traits/EmailTraitTest.php
  Tests/Unit/Traits/MakeInstanceTrait.php
  Tests/Unit/Traits/MakeInstanceTraitTest.php
Labels: enhancement

#675 [CLEANUP] Migrate EventEditor to SwiftMailer
  Classes/FrontEnd/EventEditor.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
Labels: cleanup

#676 [CLEANUP] Switch emailing in the EmailService from oelib mail functions to the Core SwiftMailer
  Classes/Service/EmailService.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
Labels: cleanup

#686 [TASK] Document how to run the tests
  CHANGELOG.md
  README.md
Labels: documentation

#660 [CLEANUP] Switch emailing in the EmailService from oelib mail functions to the Core SwiftMailer
  Classes/SchedulerTasks/MailNotifier.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
Labels: cleanup

#711 [CLEANUP] Replace Tx_Seminars_Interface_Titled usages
  Classes/ViewHelper/CommaSeparatedTitles.php
  Tests/LegacyUnit/ViewHelpers/CommaSeparatedTitlesViewHelperTest.php
Labels: bug, cleanup

#707 [CLEANUP] Replace GeneralUtility::getUserObj() with ::makeInstance
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/Email/Salutation.php
  Classes/FrontEnd/DefaultController.php
  Classes/Service/RegistrationManager.php
Labels: bug, cleanup

#710 [CLEANUP] Drop the cellspacing HTML attribute from the HTML
  Resources/Private/Templates/BackEnd/EventsList.html
  Resources/Private/Templates/BackEnd/OrganizersList.html
  Resources/Private/Templates/BackEnd/RegistrationsList.html
  Resources/Private/Templates/BackEnd/SpeakersList.html
  Resources/Private/Templates/FrontEnd/FrontEnd.html
Labels: bug

#706 [CLEANUP] Replace the laravel_tags with legacy_tests
  .github/workflows/ci.yml
Labels: bug, cleanup

#708 [CLEANUP] Replace ExtensionManagementUtility::siteRelPath('seminars')
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/EventsList.php
Labels: bug, cleanup

#709 [BUGFIX] Replace Tx_Rnbase_Configuration_Processor with Sys25\RnBase\Configuration\Processor
  Classes/FrontEnd/Editor.php
Labels: bug

#716 [CLEANUP] Stop calling ->initTemplate in TYPO3 >= 9
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/FrontEnd/EventEditorTest.php
Labels: bug, cleanup

#717 [CLEANUP] Replace Bootstrap::getInstance for TYPO3 >= 9
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
Labels: bug, cleanup

#715 [CLEANUP] Stop using Translator and TranslatorRegistry
  Classes/Email/Salutation.php
  Classes/ViewHelper/Countdown.php
  Classes/ViewHelper/DateRange.php
  Classes/ViewHelper/TimeRange.php
Labels: cleanup

#719 [CLEANUP] Replace TestingFramework->existsRecord() and ->existsExactlyOneRecord() with the new Connection class
  Tests/LegacyUnit/FrontEnd/PublishEventTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: bug, cleanup

#721 [CLEANUP] Fix a typo in a test name
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
Labels: bug, cleanup

#722 [BUGFIX] Drop the obsolete dividers2tabs option from TCA
  CHANGELOG.md
  Configuration/TCA/tx_seminars_attendances.php
  Configuration/TCA/tx_seminars_seminars.php
Labels: bug, cleanup

#723 [CLEANUP] Switch AbstractBagBuilder to PageRepository
  Classes/BagBuilder/AbstractBagBuilder.php
Labels: bug, cleanup

#724 [CLEANUP] Replace TestingFramework->countRecords with the new Connection class
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
Labels: bug, cleanup
