Repository oliverklee/ext-seminars, pull requests merged in 2021-09, with the labels that each got.

#780 [BUGFIX] Stop using `PATH_site` in TYPO3 9LTS
  CHANGELOG.md
  Classes/FrontEnd/EventEditor.php
  Classes/OldModel/Event.php
  phpstan-baseline.neon
Labels: bug, cleanup

#788 [CLEANUP] Improve the type annotations
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/Model/Event.php
  Classes/Model/Registration.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Tests/Functional/FrontEnd/RegistrationFormTest.php
  Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
  Tests/Functional/Traits/FalHelper.php
  Tests/LegacyUnit/BackEnd/AbstractModuleTest.php
  Tests/LegacyUnit/BackEnd/ControllerTest.php
  Tests/LegacyUnit/ConfigCheckTest.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php
  Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/EventTopicTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/EventStateServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
  Tests/Unit/OldModel/EventTest.php
  Tests/Unit/Traits/EmailTrait.php
  phpstan-baseline.neon
Labels: bug, cleanup

#790 [CLEANUP] Use the `class-string` pseudo-type in annotations
  CHANGELOG.md
  Classes/Email/Salutation.php
  Tests/Functional/Configuration/TypoScriptSetupTest.php
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/RealUrl/ConfigurationTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/Traits/MakeInstanceTrait.php
Labels: cleanup

#791 [CLEANUP] Use generics for the bag classes
  CHANGELOG.md
  Classes/Bag/AbstractBag.php
  Classes/Bag/Category.php
  Classes/Bag/Event.php
  Classes/Bag/Organizer.php
  Classes/Bag/Registration.php
  Classes/Bag/Speaker.php
  Classes/Bag/TimeSlot.php
  Tests/LegacyUnit/Fixtures/Bag/TestingBag.php
Labels: cleanup

#792 [CLEANUP] Use generics for the bag builder classes
  CHANGELOG.md
  Classes/BagBuilder/AbstractBagBuilder.php
  Classes/BagBuilder/Category.php
  Classes/BagBuilder/Event.php
  Classes/BagBuilder/Organizer.php
  Classes/BagBuilder/Registration.php
  Classes/BagBuilder/Speaker.php
  Tests/LegacyUnit/Fixtures/BagBuilder/BrokenBagBuilder.php
  Tests/LegacyUnit/Fixtures/BagBuilder/TestingBagBuilder.php
Labels: cleanup

#793 [CLEANUP] Use generics for the mapper classes
  CHANGELOG.md
  Classes/Mapper/BackEndUser.php
  Classes/Mapper/BackEndUserGroup.php
  Classes/Mapper/Category.php
  Classes/Mapper/Checkbox.php
  Classes/Mapper/Event.php
  Classes/Mapper/EventType.php
  Classes/Mapper/Food.php
  Classes/Mapper/FrontEndUser.php
  Classes/Mapper/FrontEndUserGroup.php
  Classes/Mapper/Lodging.php
  Classes/Mapper/Organizer.php
  Classes/Mapper/PaymentMethod.php
  Classes/Mapper/Place.php
  Classes/Mapper/Registration.php
  Classes/Mapper/Skill.php
  Classes/Mapper/Speaker.php
  Classes/Mapper/TargetGroup.php
  Classes/Mapper/TimeSlot.php
  phpstan-baseline.neon
Labels: cleanup

#797 [CLEANUP] Drop redundant type annotations for `ObjectProphecy`
  CHANGELOG.md
  Tests/Functional/Traits/FalHelper.php
  Tests/LegacyUnit/BackEnd/ControllerTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
Labels: cleanup

#796 [CLEANUP] Drop redundant type annotations
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/RegistrationsList.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/EventHeadline.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/Model/Event.php
  Classes/Model/Place.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
  Tests/Functional/Mapper/DateMapperTest.php
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/Functional/Mapper/RegistrationMapperTest.php
  Tests/Functional/Mapper/TopicMapperTest.php
  Tests/Functional/Model/SpeakerTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/OrganizersListTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BackEnd/SpeakersListTest.php
  Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/Mapper/BackEndUserMapperTest.php
  Tests/LegacyUnit/Mapper/CategoryMapperTest.php
  Tests/LegacyUnit/Mapper/CheckboxMapperTest.php
  Tests/LegacyUnit/Mapper/EventDateMapperTest.php
  Tests/LegacyUnit/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Mapper/EventTopicMapperTest.php
  Tests/LegacyUnit/Mapper/EventTypeMapperTest.php
  Tests/LegacyUnit/Mapper/FoodMapperTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserMapperTest.php
  Tests/LegacyUnit/Mapper/LodgingMapperTest.php
  Tests/LegacyUnit/Mapper/OrganizerMapperTest.php
  Tests/LegacyUnit/Mapper/PaymentMethodMapperTest.php
  Tests/LegacyUnit/Mapper/PlaceMapperTest.php
  Tests/LegacyUnit/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Mapper/SingleEventMapperTest.php
  Tests/LegacyUnit/Mapper/SkillMapperTest.php
  Tests/LegacyUnit/Mapper/SpeakerMapperTest.php
  Tests/LegacyUnit/Mapper/TargetGroupMapperTest.php
  Tests/LegacyUnit/Mapper/TimeSlotMapperTest.php
  Tests/LegacyUnit/Model/BackEndUserTest.php
  Tests/LegacyUnit/Model/EventDateTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/Model/PlaceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  phpstan-baseline.neon
Labels: cleanup

#798 [CLEANUP] Use the generics properly in the mappers
  CHANGELOG.md
  Classes/Mapper/BackEndUser.php
  Classes/Mapper/BackEndUserGroup.php
  Classes/Mapper/FrontEndUser.php
  Classes/Mapper/FrontEndUserGroup.php
  phpstan-baseline.neon
Labels: cleanup

#799 [CLEANUP] Improve the type annotations
  CHANGELOG.md
  Classes/BagBuilder/AbstractBagBuilder.php
  Classes/Csv/AbstractListView.php
  Classes/Csv/CsvDownloader.php
  Classes/FrontEnd/CategoryList.php
  Classes/Hooks/Interfaces/RegistrationEmail.php
  Classes/Model/Event.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/BackEnd/ControllerTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserMapperTest.php
  Tests/LegacyUnit/Model/AbstractTimeSpanTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/LegacyUnit/Service/EventStateServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
  Tests/Unit/Traits/EmailTrait.php
  phpstan-baseline.neon
Labels: cleanup

#800 [CLEANUP] Improve type annotations concerning the header proxy
  CHANGELOG.md
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
  phpstan-baseline.neon
Labels: cleanup

#801 [CLEANUP] Improve type annotations for mocks
  CHANGELOG.md
  Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
  Tests/LegacyUnit/Csv/BackEndEventAccessCheckTest.php
  Tests/LegacyUnit/Csv/BackEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  phpstan-baseline.neon
Labels: cleanup

#805 [CLEANUP] Use the new `HeaderProxy::getHeaderCollector()` method
  CHANGELOG.md
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
Labels: cleanup

#806 [TASK] Simplify the user and group mapper inheritance chains
  CHANGELOG.md
  Classes/Mapper/BackEndUser.php
  Classes/Mapper/BackEndUserGroup.php
  Classes/Mapper/FrontEndUser.php
  Classes/Mapper/FrontEndUserGroup.php
  Tests/Unit/Mapper/BackEndUserGroupMapperTest.php
  Tests/Unit/Mapper/BackEndUserMapperTest.php
  Tests/Unit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Unit/Mapper/FrontEndUserMapperTest.php
  phpstan-baseline.neon
Labels: bug, cleanup

#807 [CLEANUP] Improve the type annotations
  Classes/OldModel/AbstractModel.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/RegistrationDigest.php
  Classes/Service/EventStatusService.php
  Classes/ViewHelper/DateRange.php
  Classes/ViewHelper/TimeRange.php
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  phpstan-baseline.neon
Labels: cleanup

#809 [CLEANUP] Improve some more type annotations
  CHANGELOG.md
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/OldModel/Registration.php
  Classes/SchedulerTasks/MailNotifier.php
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  phpstan-baseline.neon
Labels: cleanup

#811 [BUGFIX] Fix the parameter type in the typolink creation calls
  CHANGELOG.md
  Classes/FrontEnd/CategoryList.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  phpstan-baseline.neon
Labels: bug, cleanup

#812 [CLEANUP] Paper over incorrect SwiftMailer type annotations
  CHANGELOG.md
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  phpstan-baseline.neon
Labels: cleanup

#814 [CLEANUP] Fix types for the BE module
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/AbstractModule.php
  phpstan-baseline.neon
Labels: bug, cleanup

#824 [TASK] Add mobivention as a sponsor
  Documentation/EN/Introduction/Sponsorship/Index.rst
Labels: documentation

#826 [TASK] Link to the testing distribution
  Documentation/EN/Introduction/LiveExamples.rst
  README.md
Labels: documentation

#830 [CLEANUP] Drop the `approved="yes"` from the locallang files
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/dk.locallang_db.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/fr.locallang_db.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/it.locallang_db.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/nl.locallang_db.xlf
  Resources/Private/Language/ru.locallang.xlf
  Resources/Private/Language/ru.locallang_db.xlf
Labels: cleanup

#832 [FOLLOWUP] De-deprecate the time slot wizard
  CHANGELOG.md
  Classes/BackEnd/TimeSlotWizard.php
  Classes/Hooks/DataHandlerHook.php
  ext_localconf.php
Labels: enhancement

#835 [BUGFIX] Add a missing word to the README
  README.md
Labels: documentation

#837 [BUGFIX] Require `ext-pdo` in the `composer.json`
  CHANGELOG.md
  composer.json
Labels: bug

#834 [BUGFIX] Do not duplicate places when copying them from time slots
  CHANGELOG.md
  Classes/Hooks/DataHandlerHook.php
  Classes/OldModel/Event.php
  Tests/Functional/Hooks/DataHandlerHookTest.php
  Tests/Functional/OldModel/EventTest.php
  Tests/Functional/OldModel/Fixtures/Events/EventsWithPlaces.xml
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: bug

#838 [BUGFIX] Use the correct GET parameter for the UID in the event headline
  CHANGELOG.md
  Classes/FrontEnd/EventHeadline.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
Labels: bug

#842 [CLEANUP] Stop mocking the BE user in the BE user mapper test
  Tests/Functional/Mapper/BackEndUserMapperTest.php
Labels: cleanup

#843 [TASK] Document the required MySQL/MariaDB settings for the FE editor
  CHANGELOG.md
  Documentation/DE/BekannteProbleme/Index.rst
  Documentation/EN/KnownProblems/Index.rst
Labels: documentation

#844 [TASK] Document the upgrade path
  CHANGELOG.md
  Documentation/DE/Installation/Index.rst
  Documentation/DE/Installation/Upgrading.rst
  Documentation/EN/Installation/Index.rst
  Documentation/EN/Installation/Upgrading.rst
Labels: documentation

#845 [CLEANUP] Fix Sphinx build warnings in the docs
  Documentation/DE/BekannteProbleme/Index.rst
  Documentation/EN/KnownProblems/Index.rst
Labels: bug, cleanup, documentation

#623 [CLEANUP] Rename folder `Interface` to `Interfaces` to avoid keyword naming conflict
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/FrontEnd/DefaultController.php
  Classes/Interfaces/CsvAccessCheck.php
  Classes/Interfaces/Hook/BackEndModule.php
  Classes/Interfaces/Hook/EventListView.php
  Classes/Interfaces/Hook/EventSingleView.php
  Classes/Interfaces/Titled.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: cleanup

#852 [BUGFIX] Remove duplicate classes
  CHANGELOG.md
  Classes/Interfaces/CsvAccessCheck.php
  Classes/Interfaces/Titled.php
  Classes/Model/Interfaces/Titled.php
Labels: bug, cleanup

#869 [CLEANUP] Unify the casing of "EMail" to "Email"
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Model/Organizer.php
  Classes/Model/Speaker.php
  Classes/OldModel/Event.php
  Classes/OldModel/Organizer.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/EmailService.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/Model/OrganizerTest.php
  Tests/LegacyUnit/Model/SpeakerTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
Labels: cleanup

#674 [CLEANUP] Switch emailing in the AbstractEventMailForm from oelib mail functions to the Core SwiftMailer
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/CancelEventMailForm.php
  Classes/BackEnd/ConfirmEventMailForm.php
  Classes/BackEnd/GeneralEventMailForm.php
  Classes/Interfaces/Hook/BackEndModule.php
  Classes/OldModel/Event.php
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  phpstan-baseline.neon
Labels: cleanup

#870 [CLEANUP] Unify more "EMail" to "Email"
  Tests/Functional/OldModel/RegistrationTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/Model/OrganizerTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/Model/SpeakerTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/OldModel/OrganizerTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
Labels: cleanup

#875 [BUGFIX] Stop using patches for dependencies
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
Labels: bug

#876 [BUGFIX] Stop using patches for dependencies
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
Labels: bug

#880 [BUGFIX] Use autosorting for testing category relations
  CHANGELOG.md
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: bug, cleanup

#881 [CLEANUP] Remove another use of a removed parameter
  CHANGELOG.md
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: bug, cleanup

#883 [CLEANUP] Use the dummy configuration class in the tests
  CHANGELOG.md
  Classes/Csv/AbstractListView.php
  Classes/Csv/CsvDownloader.php
  Classes/Csv/EventListView.php
  Classes/FrontEnd/EventEditor.php
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EventListViewTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
  Tests/LegacyUnit/ViewHelpers/DateRangeViewHelperTest.php
  Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php
  Tests/Unit/SchedulerTask/RegistrationDigestTest.php
Labels: cleanup

#886 [CLEANUP] Clean up the test style
  Configuration/php-cs-fixer.php
  Tests/LegacyUnit/BackEnd/AbstractModuleTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/OrganizersListTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BackEnd/SpeakersListTest.php
  Tests/LegacyUnit/Bag/AbstractBagTest.php
  Tests/LegacyUnit/Bag/CategoryBagTest.php
  Tests/LegacyUnit/Bag/EventBagTest.php
  Tests/LegacyUnit/Bag/OrganizerBagTest.php
  Tests/LegacyUnit/BagBuilder/AbstractBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/CategoryBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/OrganizerBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/SpeakerBagBuilderTest.php
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EditorTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
  Tests/LegacyUnit/FrontEnd/TestingViewTest.php
  Tests/LegacyUnit/OldModel/AbstractModelTest.php
  Tests/LegacyUnit/OldModel/OrganizerTest.php
  Tests/LegacyUnit/OldModel/TimeSlotTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#901 [CLEANUP] Add a type declaration to get oelib 4.0 to work
  CHANGELOG.md
  Classes/FrontEnd/EventEditor.php
Labels: bug, cleanup

#905 [CLEANUP] Drop autogeneratable fields from the SQL file
  CHANGELOG.md
  ext_tables.sql
Labels: cleanup

#910 [TASK] Use the new configuration class in `AbstractTimeSpan`
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/TimeSlot.php
  Tests/Functional/OldModel/AbstractTimeSpanTest.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/OldModel/TimeSlotTest.php
Labels: cleanup

#914 [TASK] Partially use the new configuration in FE tests
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/Functional/OldModel/EventTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: cleanup

#915 [TASK] Use the new configuration for the email template path
  CHANGELOG.md
  Classes/Service/RegistrationManager.php
  Tests/Functional/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#916 [CLEANUP] Use the new configuration for the waiting list settings
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#917 [CLEANUP] Switch `allowRegistrationForEventsWithoutDate` to the new config
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/OldModel/Event.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#918 [BUGFIX] Complete `extras/typo3-cms` in the `composer.json`
  CHANGELOG.md
  composer.json
Labels: bug, cleanup

#919 [CLEANUP] Switch `showTimeOfUnregistrationDeadline` to the new config
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: cleanup

#921 [CLEANUP] Move the shared configuration access to a trait
  Classes/Configuration/Traits/SharedPluginConfiguration.php
  Classes/FrontEnd/DefaultController.php
  Classes/OldModel/AbstractModel.php
  Classes/Service/RegistrationManager.php
Labels: cleanup

#924 [CLEANUP] Switch `unregistrationDeadlineDaysBeforeBeginDate` the new config
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: cleanup

#928 [CLEANUP] Switch the date and time format to the new configuration
  CHANGELOG.md
  Classes/Configuration/Traits/SharedPluginConfiguration.php
  Classes/FrontEnd/EventEditor.php
  Classes/Hooks/Interfaces/DateTimeSpan.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/Service/RegistrationManager.php
  Classes/ViewHelper/DateRange.php
  Classes/ViewHelper/TimeRange.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/OldModel/AbstractTimeSpanTest.php
  Tests/Functional/OldModel/EventTest.php
  Tests/Functional/OldModel/RegistrationTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
Labels: cleanup

#930 [CLEANUP] Switch `allowRegistrationForStartedEvents` to the new config
  CHANGELOG.md
  Classes/OldModel/Event.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingEvent.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/Unit/OldModel/Fixtures/TestingTimeSpan.php
Labels: cleanup

#941 [BUGFIX] Correct the TypoScript namespace for the config check
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
Labels: bug

#962 [TASK] Stop implementing a legacy configuration check interface
  CHANGELOG.md
  Classes/FrontEnd/AbstractView.php
  Classes/FrontEnd/DefaultController.php
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/Registration.php
  Tests/LegacyUnit/Fixtures/DummyObjectToCheck.php
Labels: cleanup

#963 [BUGFIX] Stop treating a model PID as current BE page ID
  CHANGELOG.md
  Classes/OldModel/AbstractModel.php
  Tests/LegacyUnit/OldModel/AbstractModelTest.php
  Tests/Unit/OldModel/Fixtures/TestingModelWithConfiguration.php
Labels: bug, cleanup

#964 [BUGFIX] Provide the template file path in the default controller tests
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: bug

#965 [BUGFIX] Do not continue after list view configuration problems
  Classes/FrontEnd/DefaultController.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
Labels: bug

#966 [BUGFIX] Use the dummy configuration in the tests for extension config
  CHANGELOG.md
  Tests/LegacyUnit/BackEnd/AbstractModuleTest.php
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
Labels: bug, cleanup

#967 [TASK] Add more type declarations for `BackEnd/`
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/AbstractModule.php
  Classes/BackEnd/CancelEventMailForm.php
  Classes/BackEnd/ConfirmEventMailForm.php
  Classes/BackEnd/Controller.php
  Classes/BackEnd/EventsList.php
  Classes/BackEnd/GeneralEventMailForm.php
  Classes/BackEnd/TceForms.php
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/BackEnd/EventsListTest.php
  Tests/Functional/BackEnd/Fixtures/TestingEventMailForm.php
  Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/AbstractModuleTest.php
  Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/ControllerTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/FlexFormsTest.php
  Tests/LegacyUnit/BackEnd/GeneralEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/OrganizersListTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BackEnd/SpeakersListTest.php
Labels: cleanup

#968 [CLEANUP] Add more type declarations
  CHANGELOG.md
  Classes/BagBuilder/Registration.php
  Classes/Csv/AbstractListView.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/Editor.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Mapper/Event.php
  Classes/Model/Checkbox.php
  Classes/Model/Event.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Place.php
  Classes/Model/Registration.php
  Classes/Model/TargetGroup.php
  Classes/Model/TimeSlot.php
  Classes/OldModel/AbstractModel.php
  Classes/OldModel/Event.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/EmailService.php
  Classes/Service/RegistrationManager.php
  Classes/Service/SingleViewLinkBuilder.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/FrontEnd/Fixtures/TestingDefaultController.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/Traits/MakeInstanceTrait.php
Labels: cleanup

#969 [BUGFIX] Provide a page to the fake frontend where needed
  CHANGELOG.md
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: bug

#970 [TASK] Add void return declarations in the docs
  CHANGELOG.md
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
Labels: documentation

#972 [TASK] Add void type declarations for the hooks
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/Hooks/DataHandlerHook.php
  Classes/Hooks/HookProvider.php
  Classes/Hooks/Interfaces/BackendRegistrationListView.php
  Classes/Hooks/Interfaces/RegistrationEmail.php
  Classes/Hooks/Interfaces/SeminarListView.php
  Classes/Hooks/Interfaces/SeminarRegistrationForm.php
  Classes/Hooks/Interfaces/SeminarSelectorWidget.php
  Classes/Hooks/Interfaces/SeminarSingleView.php
  Classes/Interfaces/Hook/BackEndModule.php
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/FrontEnd/Fixtures/TestingDefaultController.php
  Tests/LegacyUnit/Service/Fixtures/TestingRegistrationManager.php
  Tests/Unit/Hooks/Fixtures/TestingHookImplementor.php
  Tests/Unit/Hooks/Fixtures/TestingHookImplementorNotImplementsInterface.php
  Tests/Unit/Hooks/Fixtures/TestingHookInterface.php
  Tests/Unit/Hooks/Fixtures/TestingHookInterfaceNotExtendsHook.php
Labels: cleanup

#974 [CLEANUP] Add return type declarations for `Bag` and `BagBuilder`
  CHANGELOG.md
  Classes/Bag/AbstractBag.php
  Classes/BagBuilder/AbstractBagBuilder.php
  Classes/BagBuilder/Category.php
  Classes/BagBuilder/Event.php
  Classes/BagBuilder/Organizer.php
  Classes/BagBuilder/Registration.php
Labels: cleanup

#979 [TASK] Add more type declarations to the CSV classes
  CHANGELOG.md
  Classes/Csv/AbstractBackEndAccessCheck.php
  Classes/Csv/AbstractListView.php
  Classes/Csv/AbstractRegistrationListView.php
  Classes/Csv/CsvDownloader.php
  Classes/Csv/DownloadRegistrationListView.php
  Classes/Csv/EmailRegistrationListView.php
  Classes/Csv/EventListView.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
Labels: cleanup

#980 [BUGFIX] Drop the typo3/cms-lang dependency
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/Csv/AbstractListView.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/MailNotifierConfiguration.php
  Classes/Service/EmailService.php
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/Csv/DownloadRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EmailRegistrationListViewTest.php
  Tests/LegacyUnit/Csv/EventListViewTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Support/Traits/BackEndTestsTrait.php
  Tests/Unit/Traits/LanguageHelper.php
  composer.json
Labels: bug

#983 [CLEANUP] Add more type declarations for `FrontEnd/`
  CHANGELOG.md
  Classes/FrontEnd/AbstractView.php
  Classes/FrontEnd/CategoryList.php
  Classes/FrontEnd/Countdown.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/Editor.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/EventHeadline.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  phpstan-baseline.neon
Labels: cleanup

#984 [CLEANUP] Improve type declarations in `Hooks/`
  CHANGELOG.md
  Classes/Hooks/DataHandlerHook.php
  Classes/Hooks/Interfaces/DataSanitization.php
  Classes/Hooks/Interfaces/SeminarListView.php
  Classes/Hooks/Interfaces/SeminarRegistrationForm.php
  Classes/Hooks/Interfaces/SeminarSelectorWidget.php
Labels: cleanup

#985 [CLEANUP] Improve type annotations in `Mapper/`
  CHANGELOG.md
  Classes/Mapper/Event.php
Labels: cleanup

#988 [CLEANUP] Improve the type annotations in `Model/`
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/Model/AbstractTimeSpan.php
  Classes/Model/BackEndUser.php
  Classes/Model/Category.php
  Classes/Model/Checkbox.php
  Classes/Model/Event.php
  Classes/Model/EventType.php
  Classes/Model/Food.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Interfaces/Titled.php
  Classes/Model/Lodging.php
  Classes/Model/Organizer.php
  Classes/Model/PaymentMethod.php
  Classes/Model/Place.php
  Classes/Model/Registration.php
  Classes/Model/Skill.php
  Classes/Model/Speaker.php
  Classes/Model/TargetGroup.php
  Classes/Model/TimeSlot.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/Model/EventDateTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/EventTopicTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/Model/SpeakerTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  phpstan-baseline.neon
Labels: cleanup

#991 [CLEANUP] Improve type annotations for `SchedulerTask/`
  CHANGELOG.md
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/MailNotifierConfiguration.php
  Classes/SchedulerTasks/RegistrationDigest.php
Labels: cleanup

#993 [CLEANUP] Improve type declarations in `Service/`
  CHANGELOG.md
  Classes/Service/ConfigurationService.php
  Classes/Service/EmailService.php
  Classes/Service/EventStatusService.php
  Classes/Service/RegistrationManager.php
  Classes/Service/SingleViewLinkBuilder.php
Labels: cleanup

#994 [CLEANUP] Improve type declarations for `ViewHelper/`
  CHANGELOG.md
  Classes/ViewHelper/CommaSeparatedTitles.php
  Classes/ViewHelper/Countdown.php
  Classes/ViewHelper/DateRange.php
  Classes/ViewHelper/TimeRange.php
  Tests/LegacyUnit/ViewHelpers/CommaSeparatedTitlesViewHelperTest.php
  phpstan-baseline.neon
Labels: cleanup

#998 [CLEANUP] Declare the visibility of all class constants
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BackEnd/AbstractModule.php
  Classes/BackEnd/RegistrationsList.php
  Classes/BackEnd/TimeSlotWizard.php
  Classes/BagBuilder/Event.php
  Classes/Csv/AbstractBackEndAccessCheck.php
  Classes/Csv/AbstractListView.php
  Classes/Csv/BackEndEventAccessCheck.php
  Classes/Csv/BackEndRegistrationAccessCheck.php
  Classes/Csv/CsvDownloader.php
  Classes/FrontEnd/AbstractView.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/PublishEvent.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/Hooks/DataHandlerHook.php
  Classes/Model/Event.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Speaker.php
  Classes/OldModel/Registration.php
  Classes/OldModel/Speaker.php
  Classes/SchedulerTasks/MailNotifierConfiguration.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/FrontEnd/CategoryListTest.php
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/Hooks/DataHandlerHookTest.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/Functional/OldModel/AbstractTimeSpanTest.php
  Tests/Functional/OldModel/RegistrationTest.php
  Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
  Tests/Functional/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/ViewHelpers/CommaSeparatedTitlesViewHelperTest.php
  Tests/LegacyUnit/ViewHelpers/DateRangeViewHelperTest.php
  Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
  phpcs.xml.dist
Labels: cleanup

#1000 [CLEANUP] Improve some type annotations in functional tests
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/BackEnd/EventsListTest.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/Functional/Bag/SpeakerBagTest.php
  Tests/Functional/BagBuilder/AbstractBagBuilderTest.php
  Tests/Functional/BagBuilder/EventBagBuilderTest.php
  Tests/Functional/Configuration/TypoScriptSetupTest.php
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/Functional/FrontEnd/CategoryListTest.php
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/FrontEnd/RegistrationFormTest.php
  Tests/Functional/Hooks/DataHandlerHookTest.php
  Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/DateMapperTest.php
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/Mapper/RegistrationMapperTest.php
  Tests/Functional/Mapper/TopicMapperTest.php
  Tests/Functional/Model/SpeakerTest.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/Functional/OldModel/AbstractTimeSpanTest.php
  Tests/Functional/OldModel/RegistrationTest.php
  Tests/Functional/OldModel/SpeakerTest.php
  Tests/Functional/RealUrl/ConfigurationTest.php
  Tests/Functional/SchedulerTask/MailNotifierConfigurationTest.php
  Tests/Functional/SchedulerTask/RegistrationDigestTest.php
  Tests/Functional/Service/RegistrationManagerTest.php
Labels: cleanup

#1001 [BUGFIX] Copy `FrontEndUserMapper::findByUserName` from oelib
  CHANGELOG.md
  Classes/Mapper/FrontEndUser.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  phpstan-baseline.neon
Labels: bug

#1004 [TASK] Namespace all view helpers
  CHANGELOG.md
  Classes/FrontEnd/Countdown.php
  Classes/FrontEnd/EventHeadline.php
  Classes/Service/EmailService.php
  Classes/ViewHelpers/CommaSeparatedTitlesViewHelper.php
  Classes/ViewHelpers/CountdownViewHelper.php
  Classes/ViewHelpers/DateRangeViewHelper.php
  Classes/ViewHelpers/TimeRangeViewHelper.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/ViewHelpers/CommaSeparatedTitlesViewHelperTest.php
  Tests/LegacyUnit/ViewHelpers/CountdownViewHelperTest.php
  Tests/LegacyUnit/ViewHelpers/DateRangeViewHelperTest.php
  Tests/LegacyUnit/ViewHelpers/TimeRangeViewHelperTest.php
Labels: cleanup

#1005 [TASK] Namespace `AbstractRegistrationListView`
  CHANGELOG.md
  Classes/Csv/AbstractRegistrationListView.php
  Classes/Csv/DownloadRegistrationListView.php
  Classes/Csv/EmailRegistrationListView.php
  Classes/Hooks/Interfaces/RegistrationListCsv.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/LegacyUnit/Csv/AbstractRegistrationListViewTest.php
Labels: cleanup

#1007 [TASK] Namespace all interfaces
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/Hooks/Interfaces/BackEndModule.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
Labels: cleanup

#1008 [CLEANUP] Drop another use of a Core whitespace constant
  Classes/FrontEnd/RegistrationForm.php
  phpstan-baseline.neon
Labels: cleanup

#1010 [TASK] Namespace the `DefaultController`
  CHANGELOG.md
  Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php
  Classes/Hooks/Interfaces/SeminarListView.php
  Classes/Hooks/Interfaces/SeminarRegistrationForm.php
  Classes/Hooks/Interfaces/SeminarSingleView.php
  Classes/Service/RegistrationManager.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/Fixtures/TestingDefaultController.php
  Tests/LegacyUnit/OldModel/EventTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  ext_localconf.php
  phpstan-baseline.neon
Labels: cleanup

#1011 [TASK] Namespace the old event class
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/EventsList.php
  Classes/Bag/Event.php
  Classes/BagBuilder/Event.php
  Classes/Csv/CsvDownloader.php
  Classes/Csv/EventListView.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/Email/Salutation.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/OldModel/LegacyEvent.php
  Classes/OldModel/Registration.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/FrontEnd/RegistrationFormTest.php
  Tests/Functional/OldModel/LegacyEventTest.php
  Tests/Functional/OldModel/RegistrationTest.php
  Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingLegacyEvent.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/Fixtures/TestingDefaultController.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
  Tests/LegacyUnit/OldModel/LegacyEventTest.php
  Tests/LegacyUnit/OldModel/RegistrationTest.php
  Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/FrontEnd/RegistrationFormTest.php
  Tests/Unit/OldModel/LegacyEventTest.php
Labels: cleanup

#1012 [TASK] Namespace the event bag and event bag builder
  CHANGELOG.md
  Classes/BackEnd/EventsList.php
  Classes/Bag/EventBag.php
  Classes/BagBuilder/EventBagBuilder.php
  Classes/Csv/EventListView.php
  Classes/FrontEnd/CategoryList.php
  Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Classes/Hooks/Interfaces/SeminarListView.php
  Classes/Hooks/Interfaces/SeminarSelectorWidget.php
  Classes/OldModel/LegacyEvent.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/RegistrationManager.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/Bag/EventBagTest.php
  Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/OldModel/LegacyEventTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  phpstan-baseline.neon
Labels: cleanup

#1014 [TASK] Namespace the registration bag and bag builder
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/RegistrationsList.php
  Classes/Bag/RegistrationBag.php
  Classes/BagBuilder/RegistrationBagBuilder.php
  Classes/Csv/AbstractRegistrationListView.php
  Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/Hooks/Interfaces/BackendRegistrationListView.php
  Classes/Hooks/Interfaces/SeminarListView.php
  Classes/Service/RegistrationManager.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
Labels: cleanup

#1016 [TASK] Namespace the old registration class
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/RegistrationsList.php
  Classes/Bag/RegistrationBag.php
  Classes/Csv/AbstractRegistrationListView.php
  Classes/FrontEnd/OliverKlee/Seminars/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/OldModel/LegacyRegistration.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/OldModel/LegacyRegistrationTest.php
  Tests/Functional/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/OldModel/LegacyRegistrationTest.php
  Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/OldModel/LegacyRegistrationTest.php
  phpstan-baseline.neon
Labels: cleanup

#1017 [TASK] Namespace the remaining bag classes
  CHANGELOG.md
  Classes/BackEnd/OrganizersList.php
  Classes/BackEnd/SpeakersList.php
  Classes/Bag/CategoryBag.php
  Classes/Bag/OrganizerBag.php
  Classes/Bag/SpeakerBag.php
  Classes/Bag/TimeSlotBag.php
  Classes/BagBuilder/Category.php
  Classes/BagBuilder/Organizer.php
  Classes/BagBuilder/Speaker.php
  Classes/OldModel/LegacyEvent.php
  Classes/OldModel/TimeSlot.php
  Tests/Functional/Bag/SpeakerBagTest.php
  Tests/LegacyUnit/Bag/AbstractBagTest.php
  Tests/LegacyUnit/Bag/CategoryBagTest.php
  Tests/LegacyUnit/Bag/OrganizerBagTest.php
  Tests/LegacyUnit/OldModel/LegacyEventTest.php
  Tests/Unit/OldModel/LegacyEventTest.php
Labels: cleanup

#1019 [FOLLOWUP] Fix bogus class folder structure from refactoring
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  phpstan-baseline.neon
Labels: bug, cleanup

#1020 [TASK] Namespace the remaining bag builder classes
  CHANGELOG.md
  Classes/BackEnd/OrganizersList.php
  Classes/BackEnd/SpeakersList.php
  Classes/BagBuilder/CategoryBagBuilder.php
  Classes/BagBuilder/OrganizerBagBuilder.php
  Classes/BagBuilder/SpeakerBagBuilder.php
  Classes/FrontEnd/CategoryList.php
  Classes/Hooks/Interfaces/SeminarListView.php
  Classes/OldModel/LegacyEvent.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/BagBuilder/AbstractBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/AbstractBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/CategoryBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/OrganizerBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/SpeakerBagBuilderTest.php
Labels: cleanup

#1021 [TASK] Namespace the abstract front-end classes
  CHANGELOG.md
  Classes/FrontEnd/AbstractEditor.php
  Classes/FrontEnd/AbstractView.php
  Classes/FrontEnd/CategoryList.php
  Classes/FrontEnd/Countdown.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/EventHeadline.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RegistrationsList.php
  Classes/FrontEnd/RequirementsList.php
  Classes/FrontEnd/SelectorWidget.php
  Tests/LegacyUnit/Fixtures/FrontEnd/TestingView.php
  Tests/LegacyUnit/FrontEnd/AbstractEditorTest.php
  Tests/LegacyUnit/FrontEnd/AbstractViewTest.php
  Tests/LegacyUnit/FrontEnd/Fixtures/TestingEditor.php
  phpstan.neon
Labels: cleanup

#1026 [TASK] Namespace the event mapper
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/RegistrationsList.php
  Classes/FrontEnd/Countdown.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/EventHeadline.php
  Classes/FrontEnd/EventPublication.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RequirementsList.php
  Classes/Mapper/EventMapper.php
  Classes/Mapper/Registration.php
  Classes/Mapper/TimeSlot.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/RegistrationDigest.php
  Classes/Service/EventStatusService.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/Mapper/EventDateMapperTest.php
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/Functional/Mapper/EventTopicMapperTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/Mapper/EventDateMapperTest.php
  Tests/LegacyUnit/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Mapper/EventTopicMapperTest.php
  Tests/LegacyUnit/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Mapper/SingleEventMapperTest.php
  Tests/LegacyUnit/Mapper/TimeSlotMapperTest.php
  Tests/LegacyUnit/Model/EventDateTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/LegacyUnit/Service/EventStatusServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/Unit/SchedulerTask/RegistrationDigestTest.php
Labels: cleanup

#1028 [TASK] Namespace the registration mapper
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/RegistrationsList.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Mapper/EventMapper.php
  Classes/Mapper/FrontEndUser.php
  Classes/Mapper/RegistrationMapper.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#1030 Revert "[TASK] Include `AbstractEditor` in the PHPStan checks (#1024)"
  phpstan-baseline.neon
  phpstan.neon
Labels: bug

#1032 [TASK] Namespace the new event model
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/EventsList.php
  Classes/BagBuilder/EventBagBuilder.php
  Classes/FrontEnd/Countdown.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/EventHeadline.php
  Classes/FrontEnd/EventPublication.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Mapper/EventMapper.php
  Classes/Model/Event.php
  Classes/Model/Registration.php
  Classes/Model/TimeSlot.php
  Classes/OldModel/LegacyEvent.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/SchedulerTasks/RegistrationDigest.php
  Classes/Service/EmailService.php
  Classes/Service/EventStatusService.php
  Classes/Service/SingleViewLinkBuilder.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/Functional/OldModel/LegacyEventTest.php
  Tests/LegacyUnit/BackEnd/CancelEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/ConfirmEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/Fixtures/OldModel/TestingLegacyEvent.php
  Tests/LegacyUnit/Fixtures/Service/TestingSingleViewLinkBuilder.php
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/Fixtures/TestingDefaultController.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
  Tests/LegacyUnit/Mapper/EventDateMapperTest.php
  Tests/LegacyUnit/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Mapper/EventTopicMapperTest.php
  Tests/LegacyUnit/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Mapper/SingleEventMapperTest.php
  Tests/LegacyUnit/Mapper/TimeSlotMapperTest.php
  Tests/LegacyUnit/Model/EventDateTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/EventTopicTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/Model/SingleEventTest.php
  Tests/LegacyUnit/Model/TimeSlotTest.php
  Tests/LegacyUnit/OldModel/LegacyEventTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/EventStatusServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/SingleViewLinkBuilderTest.php
  Tests/Unit/Model/EventTest.php
  Tests/Unit/OldModel/LegacyEventTest.php
Labels: cleanup

#1033 [TASK] Namespace the new registration model
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/CancelEventMailForm.php
  Classes/BackEnd/ConfirmEventMailForm.php
  Classes/BackEnd/GeneralEventMailForm.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Hooks/Interfaces/BackEndModule.php
  Classes/Hooks/Interfaces/BackendRegistrationListView.php
  Classes/Hooks/Interfaces/RegistrationEmail.php
  Classes/Mapper/RegistrationMapper.php
  Classes/Model/Event.php
  Classes/Model/FrontEndUser.php
  Classes/Model/Registration.php
  Classes/Service/EmailService.php
  Classes/Service/RegistrationManager.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/BackEnd/Fixtures/TestingHookImplementor.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/Fixtures/TestingRegistrationManager.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  phpstan-baseline.neon
Labels: cleanup

#1034 [TASK] Namespace the new user (group) models
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/BackEnd/AbstractList.php
  Classes/BagBuilder/RegistrationBagBuilder.php
  Classes/Email/Salutation.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Mapper/BackEndUser.php
  Classes/Mapper/BackEndUserGroup.php
  Classes/Mapper/FrontEndUser.php
  Classes/Mapper/FrontEndUserGroup.php
  Classes/Mapper/RegistrationMapper.php
  Classes/Model/BackEndUser.php
  Classes/Model/BackEndUserGroup.php
  Classes/Model/Checkbox.php
  Classes/Model/Event.php
  Classes/Model/FrontEndUser.php
  Classes/Model/FrontEndUserGroup.php
  Classes/Model/Place.php
  Classes/Model/Registration.php
  Classes/Model/Speaker.php
  Classes/Model/TargetGroup.php
  Classes/OldModel/LegacyRegistration.php
  Classes/OldModel/Speaker.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/EmailService.php
  Classes/Service/RegistrationManager.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/OldModel/LegacyRegistrationTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/Csv/FrontEndRegistrationAccessCheckTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/Mapper/CheckboxMapperTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/LegacyUnit/Mapper/PlaceMapperTest.php
  Tests/LegacyUnit/Mapper/SpeakerMapperTest.php
  Tests/LegacyUnit/Mapper/TargetGroupMapperTest.php
  Tests/LegacyUnit/Model/BackEndUserGroupTest.php
  Tests/LegacyUnit/Model/BackEndUserTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/FrontEndUserGroupTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/Fixtures/EmailSalutationHookInterface.php
  Tests/LegacyUnit/Service/Fixtures/RegistrationHookInterface.php
  Tests/Unit/Mapper/BackEndUserGroupMapperTest.php
  Tests/Unit/Mapper/BackEndUserMapperTest.php
  Tests/Unit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Unit/Mapper/FrontEndUserMapperTest.php
  Tests/Unit/OldModel/LegacyRegistrationTest.php
  Tests/Unit/OldModel/SpeakerTest.php
  phpstan-baseline.neon
Labels: cleanup

#1035 [TASK] Namespace the registration manager
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/FrontEnd/RequirementsList.php
  Classes/Hooks/Interfaces/RegistrationEmail.php
  Classes/OldModel/LegacyEvent.php
  Classes/Service/RegistrationManager.php
  Documentation/DE/Referenz/Hooks/Index.rst
  Documentation/EN/Reference/Hooks/Index.rst
  Tests/Functional/FrontEnd/DefaultControllerTest.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Bag/EventBagTest.php
  Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
  Tests/LegacyUnit/Csv/CsvDownloaderTest.php
  Tests/LegacyUnit/FrontEnd/AbstractEditorTest.php
  Tests/LegacyUnit/FrontEnd/CountdownTest.php
  Tests/LegacyUnit/FrontEnd/DefaultControllerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationFormTest.php
  Tests/LegacyUnit/FrontEnd/RegistrationsListTest.php
  Tests/LegacyUnit/FrontEnd/RequirementsListTest.php
  Tests/LegacyUnit/FrontEnd/SelectorWidgetTest.php
  Tests/LegacyUnit/OldModel/LegacyEventTest.php
  Tests/LegacyUnit/OldModel/LegacyRegistrationTest.php
  Tests/LegacyUnit/Service/Fixtures/TestingRegistrationManager.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#1036 [TASK] Namespace the user (group) mappers
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Classes/Csv/FrontEndRegistrationAccessCheck.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Mapper/BackEndUserGroupMapper.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/Mapper/Checkbox.php
  Classes/Mapper/FrontEndUserGroupMapper.php
  Classes/Mapper/FrontEndUserMapper.php
  Classes/Mapper/Place.php
  Classes/Mapper/RegistrationMapper.php
  Classes/Mapper/Speaker.php
  Classes/Mapper/TargetGroup.php
  Classes/OldModel/LegacyEvent.php
  Classes/OldModel/LegacyRegistration.php
  Classes/OldModel/Speaker.php
  Classes/SchedulerTasks/MailNotifier.php
  Classes/Service/RegistrationManager.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BackEnd/OrganizersListTest.php
  Tests/LegacyUnit/BackEnd/RegistrationsListTest.php
  Tests/LegacyUnit/BackEnd/SpeakersListTest.php
  Tests/LegacyUnit/BagBuilder/RegistrationBagBuilderTest.php
  Tests/LegacyUnit/Email/SalutationTest.php
  Tests/LegacyUnit/Mapper/CheckboxMapperTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/LegacyUnit/Mapper/PlaceMapperTest.php
  Tests/LegacyUnit/Mapper/RegistrationMapperTest.php
  Tests/LegacyUnit/Mapper/SpeakerMapperTest.php
  Tests/LegacyUnit/Mapper/TargetGroupMapperTest.php
  Tests/LegacyUnit/Model/BackEndUserTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/Mapper/BackEndUserGroupMapperTest.php
  Tests/Unit/Mapper/BackEndUserMapperTest.php
  Tests/Unit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Unit/Mapper/FrontEndUserMapperTest.php
  Tests/Unit/OldModel/SpeakerTest.php
Labels: cleanup

#1037 [CLEANUP] Improve the type annotations for the mapper relations
  CHANGELOG.md
  Classes/Mapper/BackEndUserGroupMapper.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/Mapper/Checkbox.php
  Classes/Mapper/EventMapper.php
  Classes/Mapper/FrontEndUserGroupMapper.php
  Classes/Mapper/FrontEndUserMapper.php
  Classes/Mapper/Place.php
  Classes/Mapper/RegistrationMapper.php
  Classes/Mapper/Speaker.php
  Classes/Mapper/TargetGroup.php
  Classes/Mapper/TimeSlot.php
Labels: cleanup
