Repository oliverklee/ext-seminars, pull requests merged in 2022-11, with the labels that each got.

#1720 [TASK] Add links to the feature survey in a few places
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Documentation/Index.rst
  README.md
Labels: enhancement, documentation

#1731 [FEATURE] Add an `AccommodationOption` model
  CHANGELOG.md
  Classes/Domain/Model/AccommodationOption.php
  Classes/Domain/Repository/AccommodationOptionRepository.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/AccommodationOptionRepositoryTest.php
  Tests/Functional/Domain/Repository/Fixtures/AccommodationOptionRepository/AccommodationOptionWithAllFields.xml
  Tests/Unit/Domain/Model/AccommodationOptionTest.php
  ext_typoscript_setup.txt
  phpstan-baseline.neon
Labels: enhancement

#1735 [CLEANUP] Move the date span rendering into a partial
  Resources/Private/Partials/EventDate.html
  Resources/Private/Templates/FrontEndEditor/Index.html
Labels: cleanup

#1734 [CLEANUP] Stop using Prophecy for `ObjectManager(Interface)`
  CHANGELOG.md
  Tests/Functional/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/Unit/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Unit/Domain/Repository/EventTypeRepositoryTest.php
  Tests/Unit/Domain/Repository/OrganizerRepositoryTest.php
  Tests/Unit/Domain/Repository/SpeakerRepositoryTest.php
  Tests/Unit/Domain/Repository/VenueRepositoryTest.php
Labels: cleanup

#1736 [TASK] Add unit tests for `AccommodationOptionRepository`
  CHANGELOG.md
  Tests/Unit/Domain/Repository/AccommodationOptionRepositoryTest.php
Labels: enhancement

#1737 [CLEANUP] Stop using Prophecy in null object tests
  CHANGELOG.md
  Tests/Unit/Rendering/NullRenderingContextTest.php
  Tests/Unit/Rendering/NullRequestTest.php
Labels: cleanup

#1738 [FEATURE] Add a `FoodOption` model
  CHANGELOG.md
  Classes/Domain/Model/FoodOption.php
  Classes/Domain/Repository/FoodOptionRepository.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/Fixtures/FoodOptionRepository/FoodOptionWithAllFields.xml
  Tests/Functional/Domain/Repository/FoodOptionRepositoryTest.php
  Tests/Unit/Domain/Model/FoodOptionTest.php
  Tests/Unit/Domain/Repository/FoodOptionRepositoryTest.php
  ext_typoscript_setup.txt
  phpstan-baseline.neon
Labels: enhancement

#1739 [CLEANUP] Stop using Prophecy in `FrontEndEditorControllerTest`
  CHANGELOG.md
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
Labels: cleanup

#1740 [FEATURE] Add a `PaymentMethod` model
  CHANGELOG.md
  Classes/Domain/Model/PaymentMethod.php
  Classes/Domain/Repository/PaymentMethodRepository.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/Fixtures/PaymentMethodRepository/PaymentMethodWithAllFields.xml
  Tests/Functional/Domain/Repository/PaymentMethodRepositoryTest.php
  Tests/Unit/Domain/Model/PaymentMethodTest.php
  Tests/Unit/Domain/Repository/PaymentMethodRepositoryTest.php
  ext_typoscript_setup.txt
  phpstan-baseline.neon
Labels: enhancement

#1742 [FEATURE] Add a `RegistrationCheckbox` model
  CHANGELOG.md
  Classes/Domain/Model/RegistrationCheckbox.php
  Classes/Domain/Repository/RegistrationCheckboxRepository.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/Fixtures/RegistrationCheckboxRepository/RegistrationCheckboxWithAllFields.xml
  Tests/Functional/Domain/Repository/RegistrationCheckboxRepositoryTest.php
  Tests/Unit/Domain/Model/RegistrationCheckboxTest.php
  Tests/Unit/Domain/Repository/RegistrationCheckboxRepositoryTest.php
  ext_typoscript_setup.txt
  phpstan-baseline.neon
Labels: enhancement

#1745 [BUGFIX] Do not reuse mocks in tests
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
Labels: bug, cleanup

#1746 [CLEANUP] Drop more Prophecy usages
  CHANGELOG.md
  Tests/Functional/BackEnd/ControllerTest.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/SchedulerTasks/MailNotifierTest.php
  Tests/Functional/Traits/FalHelper.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  phpstan-baseline.neon
Labels: cleanup

#1741 [CLEANUP] Drop the remaining Prophecy usages
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
Labels: cleanup

#1748 [TASK] Also allow installations with Emogrifier 7
  CHANGELOG.md
  composer.json
Labels: dependencies

#1750 [FEATURE] Add a basic `Registration` model
  CHANGELOG.md
  Classes/Domain/Model/Registration.php
  Classes/Domain/Repository/RegistrationRepository.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/Fixtures/RegistrationRepository/RegistrationOnPage.xml
  Tests/Functional/Domain/Repository/Fixtures/RegistrationRepository/RegistrationWithAllFields.xml
  Tests/Functional/Domain/Repository/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/RegistrationTest.php
  Tests/Unit/Domain/Repository/RegistrationRepositoryTest.php
  ext_typoscript_setup.txt
  phpstan-baseline.neon
Labels: enhancement

#1752 [FEATURE] Add `Registration.event` and `.user`
  CHANGELOG.md
  Classes/Domain/Model/Registration.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/Fixtures/RegistrationRepository/RegistrationWithEventDate.xml
  Tests/Functional/Domain/Repository/Fixtures/RegistrationRepository/RegistrationWithEventTopic.xml
  Tests/Functional/Domain/Repository/Fixtures/RegistrationRepository/RegistrationWithSingleEvent.xml
  Tests/Functional/Domain/Repository/Fixtures/RegistrationRepository/RegistrationWithUser.xml
  Tests/Functional/Domain/Repository/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/RegistrationTest.php
  ext_typoscript_setup.txt
Labels: enhancement

#1754 [BUGFIX] Fix a typo in a `Registration` model setter
  CHANGELOG.md
  Classes/Model/Registration.php
  Tests/LegacyUnit/Model/RegistrationTest.php
Labels: bug

#1756 [TASK] Move part of the `Registration` model to an `AttendeesTrait`
  CHANGELOG.md
  Classes/Domain/Model/Registration/AttendeesTrait.php
  Classes/Domain/Model/Registration/Registration.php
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
Labels: cleanup

#1757 [FEATURE] Add scalar fields to the `Registration` model
  CHANGELOG.md
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Registration/AttendeesTrait.php
  Classes/Domain/Model/Registration/BillingAddressTrait.php
  Classes/Domain/Model/Registration/PaymentTrait.php
  Classes/Domain/Model/Registration/Registration.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithAllFields.xml
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
  ext_typoscript_setup.txt
Labels: enhancement

#1758 [FEATURE] Add more associations to the `Registration` model
  CHANGELOG.md
  Classes/Domain/Model/Registration/AttendeesTrait.php
  Classes/Domain/Model/Registration/PaymentTrait.php
  Classes/Domain/Model/Registration/Registration.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithAccommodationOption.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithAdditionalPerson.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithFoodOption.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithPaymentMethod.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithRegistrationCheckbox.xml
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
  ext_typoscript_setup.txt
Labels: enhancement

#1766 [CLEANUP] Stop relying on the iteration pointer in repository tests
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
Labels: cleanup

#1767 [FEATURE] Add registration-specific associations to the `Event` model
  CHANGELOG.md
  Classes/Domain/Model/Event/EventDate.php
  Classes/Domain/Model/Event/EventDateInterface.php
  Classes/Domain/Model/Event/EventDateTrait.php
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Event/EventTopic.php
  Classes/Domain/Model/Event/EventTopicTrait.php
  Classes/Domain/Model/Event/SingleEvent.php
  Configuration/Extbase/Persistence/Classes.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateWithAccommodationOption.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateWithFoodOption.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventDateWithRegistrationCheckbox.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/EventTopicWithPaymentMethod.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithAccommodationOption.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithFoodOption.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithPaymentMethod.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventRepository/SingleEventWithRegistrationCheckbox.xml
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/EventTopicTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
  ext_typoscript_setup.txt
Labels: enhancement

#1768 [CLEANUP] Drop unnecessary directory level for fixtures
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateAndTopicWithAllFields.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateAndTopicWithEventType.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateAndTopicWithoutData.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateWithAccommodationOption.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateWithFoodOption.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateWithOrganizer.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateWithOwner.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateWithRegistrationCheckbox.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateWithSpeaker.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateWithVenue.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventTopicWithAllFields.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventTopicWithEventType.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventTopicWithOwner.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventTopicWithPaymentMethod.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithAccommodationOption.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithAllFields.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithEventType.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithFoodOption.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithOrganizer.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithOwner.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithOwnerOnPage.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithPaymentMethod.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithRegistrationCheckbox.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithSpeaker.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithVenue.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithoutData.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithoutOwner.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/TwoSingleEventsWithOwner.xml
Labels: cleanup

#1771 [FEATURE] Add a `Price` model
  CHANGELOG.md
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Price.php
  Classes/Domain/Model/Registration/PaymentTrait.php
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/PriceTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
Labels: enhancement

#1791 [FEATURE] Add `Event.isFreeOfCharge()`
  CHANGELOG.md
  Classes/Domain/Model/Event/EventDate.php
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Event/EventTopicTrait.php
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/EventTopicTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
Labels: enhancement

#1793 [FEATURE] Add getters for event prices
  CHANGELOG.md
  Classes/Domain/Model/Event/EventDate.php
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Event/EventTopicTrait.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/EventTopicTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
Labels: enhancement

#1794 [CLEANUP] Flip the guard clauses in `EventDate`
  Classes/Domain/Model/Event/EventDate.php
Labels: cleanup

#1797 [CLEANUP] Use the new event status constants in more places
  Classes/BagBuilder/EventBagBuilder.php
  Classes/Mapper/EventMapper.php
  Classes/OldModel/LegacyEvent.php
  Classes/SchedulerTasks/MailNotifier.php
  Configuration/TCA/tx_seminars_seminars.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/BagBuilder/EventBagBuilderTest.php
  Tests/LegacyUnit/FrontEnd/CategoryListTest.php
  Tests/LegacyUnit/Mapper/EventMapperTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/OldModel/LegacyEventTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/Service/EventStatusServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: cleanup

#1800 [BUGFIX] Fix incorrect PHPDoc references to price code constants
  Classes/Domain/Model/Event/EventDate.php
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Event/EventTopicTrait.php
Labels: bug, cleanup

#1799 [FEATURE] Add a `PriceFinder` class
  CHANGELOG.md
  Classes/Domain/Model/Event/EventDateInterface.php
  Classes/Service/PriceFinder.php
  Tests/Unit/Service/PriceFinderTest.php
Labels: enhancement

#1801 [TASK] Switch the new models from `DateTime` to `DateTimeImmutable`
  CHANGELOG.md
  Classes/Domain/Model/Event/EventDateInterface.php
  Classes/Domain/Model/Event/EventDateTrait.php
  Classes/Service/PriceFinder.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
  Tests/Unit/Service/PriceFinderTest.php
Labels: cleanup

#1813 [FEATURE] Add and use a `Translate` trait
  CHANGELOG.md
  Classes/Csv/CsvDownloader.php
  Classes/Localization/TranslateTrait.php
  Classes/OldModel/AbstractModel.php
  Resources/Private/Language/locallang.xlf
  Tests/Functional/Localization/TranslateTraitTest.php
  phpstan-baseline.neon
Labels: enhancement, cleanup

#1818 [FEATURE] Add a `SalutationAwareTranslateViewHelper`
  CHANGELOG.md
  Classes/ViewHelpers/SalutationAwareTranslateViewHelper.php
  Resources/Private/Language/locallang.xlf
  Tests/Functional/ViewHelpers/Fixtures/BackEndUser.xml
  Tests/Functional/ViewHelpers/SalutationAwareTranslateViewHelperTest.php
  Tests/Unit/ViewHelpers/SalutationAwareTranslateViewHelperTest.php
  phpstan-baseline.neon
Labels: enhancement

#1821 [FEATURE] Add `Registration.hasSeparateBillingAddress`
  CHANGELOG.md
  Classes/Domain/Model/Registration/BillingAddressTrait.php
  Configuration/TCA/tx_seminars_attendances.php
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang_db.xlf
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithAllFields.xml
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
  ext_tables.sql
Labels: enhancement

#1822 [BUGFIX] Fix `SalutationAwareTranslateViewHelper` tests in 11LTS
  CHANGELOG.md
  Tests/Functional/ViewHelpers/SalutationAwareTranslateViewHelperTest.php
Labels: bug

#1826 [BUGFIX] Fix renderings warnings in the documentation
  CHANGELOG.md
  Documentation/DE/Konfiguration/SettingUpFront-endEditing/Index.rst
  Documentation/EN/Configuration/SettingUpFront-endEditing/Index.rst
Labels: bug, documentation

#1827 [BUGFIX] Drop extraneous whitespace in a configuration check message
  Classes/Configuration/SharedConfigurationCheck.php
Labels: bug, cleanup

#1825 [FEATURE] Add a plugin for event registration
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Configuration/FlexForms/EventRegistration.xml
  Configuration/TCA/Overrides/tt_content.php
  Documentation/EN/Installation/AddingPagesToTheFrontEnd/Index.rst
  Documentation/EN/Installation/GetAFront-endUserLogin(anyPossiblyRegistration)Running/Index.rst
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Layouts/EventRegistration.html
  Resources/Private/Templates/EventRegistration/CheckPrerequisites.html
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  ext_localconf.php
  phpstan-baseline.neon
Labels: enhancement

#1651 [TASK] Allow more versions of mkforms
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: dependencies

#1829 [FEATURE] Add `Event.allowsUnlimitedRegistrations()`
  CHANGELOG.md
  Classes/Domain/Model/Event/EventDateInterface.php
  Classes/Domain/Model/Event/EventDateTrait.php
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
Labels: enhancement

#1830 [FEATURE] Adapt the registration links to the new registration form
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/Service/RegistrationManager.php
  phpstan-baseline.neon
Labels: enhancement

#1835 [FEATURE] Add `Event.isRegistrationPossibleForThisClass`
  CHANGELOG.md
  Classes/Domain/Model/Event/Event.php
  Classes/Domain/Model/Event/EventDate.php
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Event/EventTopic.php
  Classes/Domain/Model/Event/SingleEvent.php
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/EventTopicTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
Labels: enhancement

#1837 [CLEANUP] Rename some variables in the tests
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
Labels: cleanup

#1840 [FEATURE] Add `RegistrationRepository.existsRegistrationForEventAndUser()`
  CHANGELOG.md
  Classes/Domain/Repository/Registration/RegistrationRepository.php
  Tests/Functional/Domain/Repository/Registration/Fixtures/DeletedRegistrationWithEventAndUser.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenRegistrationWithEventAndUser.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithEventAndUser.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithEventAndUserAndAdditionalEvent.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/TwoRegistrationsWithSameEventAndUser.xml
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  phpstan-baseline.neon
Labels: enhancement

#1845 [CLEANUP] Drop unused repository from controller
  Classes/Controller/EventRegistrationController.php
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  phpstan-baseline.neon
Labels: cleanup

#1846 [FEATURE] Add `RegistrationGuard.isUserBlocked()`
  CHANGELOG.md
  Classes/Domain/Repository/Registration/RegistrationRepository.php
  Classes/Service/RegistrationGuard.php
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: enhancement

#1848 [FEATURE] Add `EventRegistrationController.denyRegistrationAction`
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Templates/EventRegistration/DenyRegistration.html
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  ext_localconf.php
Labels: enhancement

#1852 [CLEANUP] Improve type annotations in `EventRegistrationController`
  Classes/Controller/EventRegistrationController.php
Labels: cleanup

#1854 [CLEANUP] Simplify `RegistrationGuardTest`
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: cleanup

#1855 [FEATURE] Check that registration is possible at all
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Classes/Service/RegistrationGuard.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Templates/EventRegistration/DenyRegistration.html
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  Tests/Unit/Service/RegistrationGuardTest.php
  phpstan-baseline.neon
Labels: enhancement

#1856 [TASK] Remove `Event.isRegistrationPossibleForThisClass()`
  Classes/Domain/Model/Event/Event.php
  Classes/Domain/Model/Event/EventDate.php
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Event/EventTopic.php
  Classes/Domain/Model/Event/SingleEvent.php
  Classes/Service/RegistrationGuard.php
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/EventTopicTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
  phpstan-baseline.neon
Labels: cleanup

#1857 [TASK] Add the issue number of removal ticket to `@deprecated` notices
  Classes/BagBuilder/EventBagBuilder.php
  Classes/Configuration/CsvExportConfigurationCheck.php
  Classes/Configuration/EventEditorConfigurationCheck.php
  Classes/Configuration/RegistrationFormConfigurationCheck.php
  Classes/Configuration/SharedConfigurationCheck.php
  Classes/Configuration/SingleViewConfigurationCheck.php
  Classes/Email/Salutation.php
  Classes/FrontEnd/AbstractEditor.php
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/EventEditor.php
  Classes/FrontEnd/EventPublication.php
  Classes/FrontEnd/RegistrationForm.php
  Classes/Model/Event.php
  Classes/Model/Registration.php
  Classes/OldModel/LegacyEvent.php
  Classes/OldModel/LegacyRegistration.php
  Classes/Service/RegistrationManager.php
  Configuration/TCA/tx_seminars_attendances.php
  Configuration/TCA/tx_seminars_seminars.php
  Configuration/TypoScript/Forms/EventEditor.typoscript
  Configuration/TypoScript/Forms/RegistrationStep1.typoscript
  Configuration/TypoScript/Forms/RegistrationStep2.typoscript
  Configuration/TypoScript/Forms/Unregistration.typoscript
  Configuration/TypoScript/FrontEnd.typoscript
  Configuration/TypoScript/PluginShared.typoscript
  Documentation/DE/Referenz/SetupForTheSeminarmanagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
  Documentation/EN/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
  ext_tables.sql
Labels: documentation

#1861 [FEATURE] Show error message if registration is not possible now
  Classes/Controller/EventRegistrationController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Tests/Unit/Controller/EventRegistrationControllerTest.php
Labels: enhancement

#1865 [FEATURE] Add and use a `OneTimeAccountConnector`
  CHANGELOG.md
  Classes/Service/OneTimeAccountConnector.php
  Classes/Service/RegistrationGuard.php
  Tests/Unit/Service/OneTimeAccountConnectorTest.php
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: enhancement

#1871 [FEATURE] Add the remaining actions for the registration form
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Configuration/TypoScript/PluginSettings.typoscript
  Configuration/TypoScript/constants.typoscript
  Configuration/TypoScript/setup.typoscript
  Documentation/EN/Installation/Upgrading.rst
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Private/Templates/EventRegistration/ThankYou.html
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  ext_localconf.php
Labels: enhancement

#1873 [FEATURE] Redirect from the registration form to the login page
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Tests/Unit/Controller/EventRegistrationControllerTest.php
Labels: enhancement

#1875 [BUGFIX] Update the `.editorconfig` and TypoScript lint settings
  .editorconfig
  CHANGELOG.md
  Configuration/TsLint.yml
  Configuration/TypoScript/Config.typoscript
  Configuration/TypoScript/CsvExport.typoscript
  Configuration/TypoScript/Forms/EventEditor.typoscript
  Configuration/TypoScript/Forms/RegistrationStep1.typoscript
  Configuration/TypoScript/Forms/RegistrationStep2.typoscript
  Configuration/TypoScript/Forms/Unregistration.typoscript
  Configuration/TypoScript/FrontEnd.typoscript
  Configuration/TypoScript/ListView.typoscript
  Configuration/TypoScript/Page.typoscript
  Configuration/TypoScript/PluginSettings.typoscript
  Configuration/TypoScript/PluginShared.typoscript
  Configuration/TypoScript/Publication.typoscript
  Configuration/TypoScript/RegistrationDigestEmail.typoscript
  Configuration/TypoScript/constants.typoscript
  ext_typoscript_setup.txt
Labels: bug, cleanup

#1883 [FEATURE] Add a test that `Registration` models can be persisted
  CHANGELOG.md
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
Labels: enhancement

#1886 [FEATURE] Check if the user is already registered for an event
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
  Resources/Private/Templates/EventRegistration/DenyRegistration.html
  Tests/Unit/Controller/EventRegistrationControllerTest.php
Labels: enhancement

#1889 [FEATURE] Polish the heading on the registration page
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Partials/EventRegistration/Headline.html
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Private/Templates/EventRegistration/ThankYou.html
Labels: enhancement

#1890 [FEATURE] Add buttons to the registration form
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
Labels: enhancement

#1892 [FEATURE] Pass a `Registration` around in the registration form
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Tests/Unit/Controller/EventRegistrationControllerTest.php
Labels: enhancement

#1893 [FEATURE] Add a notes field to the registration form
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/EventRegistration/Headline.html
  Resources/Private/Partials/EventRegistration/ValidationResult.html
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
Labels: enhancement

#1896 [FEATURE] Add a back button to the registration form
  CHANGELOG.md
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
Labels: enhancement

#1898 [FEATURE] Add a configuration for the registration storage folder
  CHANGELOG.md
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
Labels: enhancement

#1900 [BUGFIX] Always load all dependencies in the functional tests
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/BackEnd/ControllerTest.php
  Tests/Functional/BackEnd/EventsListTest.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/Functional/Bag/SpeakerBagTest.php
  Tests/Functional/BagBuilder/AbstractBagBuilderTest.php
  Tests/Functional/BagBuilder/EventBagBuilderTest.php
  Tests/Functional/Configuration/CsvExportConfigurationCheckTest.php
  Tests/Functional/Configuration/RegistrationFormConfigurationCheckTest.php
  Tests/Functional/Configuration/RegistrationListConfigurationCheckTest.php
  Tests/Functional/Configuration/SharedConfigurationCheckTest.php
  Tests/Functional/Configuration/TypoScriptSetupTest.php
  Tests/Functional/Csv/CsvDownloaderTest.php
  Tests/Functional/Domain/Repository/AccommodationOptionRepositoryTest.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Functional/Domain/Repository/EventTypeRepositoryTest.php
  Tests/Functional/Domain/Repository/FoodOptionRepositoryTest.php
  Tests/Functional/Domain/Repository/OrganizerRepositoryTest.php
  Tests/Functional/Domain/Repository/PaymentMethodRepositoryTest.php
  Tests/Functional/Domain/Repository/RegistrationCheckboxRepositoryTest.php
  Tests/Functional/Domain/Repository/SpeakerRepositoryTest.php
  Tests/Functional/Domain/Repository/VenueRepositoryTest.php
  Tests/Functional/FrontEnd/CategoryListTest.php
  Tests/Functional/FrontEnd/DefaultController/ListViewTest.php
  Tests/Functional/FrontEnd/DefaultController/PluginDefinitionTest.php
  Tests/Functional/FrontEnd/DefaultController/SingleViewTest.php
  Tests/Functional/FrontEnd/EventEditorTest.php
  Tests/Functional/FrontEnd/EventHeadlineTest.php
  Tests/Functional/FrontEnd/RegistrationFormTest.php
  Tests/Functional/Hooks/DataHandlerHookTest.php
  Tests/Functional/Localization/TranslateTraitTest.php
  Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/Functional/Mapper/EventDateMapperTest.php
  Tests/Functional/Mapper/EventMapperTest.php
  Tests/Functional/Mapper/EventTopicMapperTest.php
  Tests/Functional/Mapper/FrontEndUserGroupMapperTest.php
  Tests/Functional/Mapper/FrontEndUserMapperTest.php
  Tests/Functional/Mapper/RegistrationMapperTest.php
  Tests/Functional/Model/SpeakerTest.php
  Tests/Functional/OldModel/AbstractModelTest.php
  Tests/Functional/OldModel/AbstractTimeSpanTest.php
  Tests/Functional/OldModel/LegacyCategoryTest.php
  Tests/Functional/OldModel/LegacyEventTest.php
  Tests/Functional/OldModel/LegacyRegistrationTest.php
  Tests/Functional/OldModel/LegacySpeakerTest.php
  Tests/Functional/SchedulerTasks/MailNotifierConfigurationTest.php
  Tests/Functional/SchedulerTasks/MailNotifierTest.php
  Tests/Functional/SchedulerTasks/RegistrationDigestTest.php
  Tests/Functional/Service/RegistrationManagerTest.php
  Tests/Functional/Service/SingleViewLinkBuilderTest.php
  Tests/Functional/UpgradeWizards/CategoryIconToFalUpgradeWizardTest.php
  Tests/Functional/UpgradeWizards/SeminarAttachmentsToFalUpgradeWizardTest.php
  Tests/Functional/UpgradeWizards/SeminarImageToFalUpgradeWizardTest.php
  Tests/Functional/ViewHelpers/CountdownViewHelperTest.php
  Tests/Functional/ViewHelpers/SalutationAwareTranslateViewHelperTest.php
Labels: bug

#1901 [CLEANUP] Improve the naming of a `RegistrationGuard` method
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Classes/Service/RegistrationGuard.php
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: cleanup

#1903 [BUGFIX] Require feuserextrafields >= 3.2.1
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: bug, dependencies

#1902 [FEATURE] Add a `RegistrationProcessor`
  CHANGELOG.md
  Classes/Service/RegistrationProcessor.php
  Tests/Unit/Service/RegistrationProcessorTest.php
Labels: enhancement

#1899 [FEATURE] Persist the registration after the form has been submitted
  Classes/Controller/EventRegistrationController.php
  Tests/Unit/Controller/EventRegistrationControllerTest.php
Labels: enhancement

#1906 [FEATURE] Add a thank-you message to the registration page
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/ThankYou.html
Labels: enhancement

#1907 [FEATURE] Add some bridge code to `RegistrationManager`
  Classes/Service/RegistrationManager.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/Service/RegistrationManagerTest.php
Labels: enhancement

#1912 [FEATURE] Add a `LegacyRegistrationConfiguration`
  Classes/Configuration/LegacyRegistrationConfiguration.php
  Tests/Unit/Configuration/LegacyRegistrationConfigurationTest.php
Labels: enhancement

#1915 [BUGFIX] Make the `RegistrationManager` injectable
  CHANGELOG.md
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RequirementsList.php
  Classes/Service/RegistrationManager.php
  Configuration/Services.yaml
  Tests/Functional/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: bug

#1927 [FEATURE] Add TypoScript settings for the Fluid templates
  CHANGELOG.md
  Configuration/TypoScript/View.typoscript
  Configuration/TypoScript/setup.typoscript
Labels: enhancement

#1930 [BUGFIX] Fix a typo in a test name
  Tests/Unit/Service/RegistrationManagerTest.php
Labels: cleanup

#1932 [FEATURE] Build the registration title after receiving a registration
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Classes/Service/RegistrationProcessor.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Tests/Functional/Service/RegistrationProcessorTest.php
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  phpstan-baseline.neon
Labels: enhancement

#1937 [BUGFIX] Refuse registration if an event date has lost its topic
  CHANGELOG.md
  Classes/Service/RegistrationGuard.php
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: bug

#1939 [CLEANUP] Drop the debugging alerts in the registration templates
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Private/Templates/EventRegistration/ThankYou.html
Labels: cleanup

#1942 [FEATURE] Update the `Event.registrations` counter cache
  CHANGELOG.md
  Classes/Domain/Repository/Event/EventRepository.php
  Classes/Service/RegistrationProcessor.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithDeletedRegistrationWithZeroCounterCache.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithHiddenRegistrationWithZeroCounterCache.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventWithTwoRegistrationsWithZeroCounterCache.xml
  Tests/Unit/Service/RegistrationProcessorTest.php
Labels: enhancement

#1948 [FEATURE] Destroy the onetimeaccount session after a registration
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Classes/Service/OneTimeAccountConnector.php
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  Tests/Unit/Service/OneTimeAccountConnectorTest.php
Labels: enhancement

#1950 [FEATURE] Add `Registration.backgroundKnowledge`
  CHANGELOG.md
  Classes/Domain/Model/Registration/Registration.php
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithAllFields.xml
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
Labels: enhancement

#1953 [FEATURE] Add fieldsets to the registration form
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
  Resources/Private/Templates/EventRegistration/New.html
Labels: enhancement

#1957 [FEATURE] Add seats to the registration form
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Public/CSS/FrontEnd/FrontEnd.css
  Tests/Unit/Controller/EventRegistrationControllerTest.php
Labels: enhancement

#1959 [TASK] Streamline the HTML and CSS for the FE editor
  CHANGELOG.md
  Resources/Private/Partials/FrontEndEditor/Form.html
  Resources/Public/CSS/FrontEnd/FrontEnd.css
Labels: bug, cleanup

#1961 [BUGFIX] Use `DateTime` instead of `DateTimeImmutable` in models
  CHANGELOG.md
  Classes/Domain/Model/Event/EventDateInterface.php
  Classes/Domain/Model/Event/EventDateTrait.php
  Classes/Service/PriceFinder.php
  Classes/Service/RegistrationGuard.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Functional/Service/RegistrationProcessorTest.php
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
  Tests/Unit/Service/PriceFinderTest.php
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: bug

#1964 [CLEANUP] Autoformat the JavaScript file
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Labels: cleanup

#1965 [TASK] Convert some JavaScript to vanilla JavaScript
  CHANGELOG.md
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Labels: cleanup

#1966 [FEATURE] Add a "register myself" checkbox to the registration form
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
Labels: enhancement

#1967 [FEATURE] Make the default value of `registeredThemselves` configurable
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Tests/Unit/Controller/EventRegistrationControllerTest.php
Labels: enhancement

#1968 [FEATURE] Add tabs to the registration form flexforms
  CHANGELOG.md
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
Labels: enhancement

#1975 [CLEANUP] Drop unnecessary `f:then` from a template
  Resources/Private/Templates/EventRegistration/Confirm.html
Labels: cleanup

#1974 [FEATURE] Add the billing address fields to the registration form
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Public/CSS/FrontEnd/FrontEnd.css
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Labels: enhancement

#1977 [FEATURE] Add food and accomodation options to the registration form
  CHANGELOG.md
  Classes/Domain/Model/Registration/Registration.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
Labels: enhancement

#1979 [FEATURE] Add the attendees names to the registration form
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Labels: enhancement

#1980 [BUGFIX] Hide labels for empty multiselects on the confirmation page
  Resources/Private/Templates/EventRegistration/Confirm.html
Labels: bug

#1981 [TASK] Render newlines from textareas on the confirmation page
  Resources/Private/Templates/EventRegistration/Confirm.html
Labels: bug, enhancement

#1982 [FEATURE] Add the payment method to the registration form
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
Labels: enhancement

#1988 [FEATURE] Add a price selector to the registation form
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Tests/Unit/Controller/EventRegistrationControllerTest.php
Labels: enhancement

#1996 [FEATURE] Add `Registration.priceCode`
  CHANGELOG.md
  Classes/Domain/Model/Registration/PaymentTrait.php
  Configuration/Extbase/Persistence/Classes.php
  Configuration/TCA/tx_seminars_attendances.php
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang_db.xlf
  Tests/Functional/Domain/Repository/Registration/Fixtures/RegistrationWithAllFields.xml
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
  ext_tables.sql
  ext_typoscript_setup.txt
Labels: enhancement

#2001 [FEATURE] Add a calculation for the total price
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Classes/Domain/Model/Price.php
  Classes/Domain/Model/Registration/PaymentTrait.php
  Classes/Service/RegistrationProcessor.php
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  Tests/Unit/Domain/Model/PriceTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
  Tests/Unit/Service/RegistrationProcessorTest.php
Labels: enhancement

#2002 [FEATURE] Validate `Registration.seats` to be >= 1
  CHANGELOG.md
  Classes/Domain/Model/Registration/AttendeesTrait.php
Labels: enhancement

#2005 [FEATURE] Display formatted price amounts in the registration form
  CHANGELOG.md
  Configuration/TypoScript/PluginSettings.typoscript
  Configuration/TypoScript/constants.typoscript
  Documentation/EN/Configuration/ChangingTheLocalizedStrings/Index.rst
  Documentation/EN/Configuration/ConfiguringPrices/Index.rst
  Documentation/EN/Installation/Upgrading.rst
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
  Resources/Private/Partials/Price.html
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
Labels: enhancement

#2006 [FEATURE] Add a registration summary to the confirmation page
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
  Resources/Private/Partials/EventRegistration/EventTitleAndDateAndUid.html
  Resources/Private/Partials/EventRegistration/Headline.html
  Resources/Private/Templates/EventRegistration/Confirm.html
Labels: enhancement

#2008 [TASK] Improve accessibility in the registration form
  CHANGELOG.md
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Public/CSS/FrontEnd/FrontEnd.css
Labels: bug, enhancement

#2009 [TASK] Hide duplicate labels from assitive technology
  CHANGELOG.md
  Resources/Private/Templates/EventRegistration/New.html
Labels: bug

#2017 [FEATURE] Add two terms & conditions checkboxes to the registration form
  CHANGELOG.md
  Classes/Domain/Model/Registration/Registration.php
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
Labels: enhancement

#2019 [FEATURE] Add registration checkboxes to the registration form
  CHANGELOG.md
  Classes/Domain/Model/Registration/Registration.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
Labels: enhancement

#2026 [CLEANUP] Make all `Price` properties transient
  CHANGELOG.md
  Classes/Domain/Model/Price.php
Labels: cleanup

#2030 [BUGFIX] Fix mapping error submitting the registration form
  CHANGELOG.md
  Resources/Private/Templates/EventRegistration/Confirm.html
Labels: bug

#2031 [FEATURE] Add validation for the terms and conditions
  CHANGELOG.md
  Classes/Domain/Model/Registration/Registration.php
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
Labels: enhancement

#2035 [TASK] Make some registration form labels reusable
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
Labels: cleanup

#2037 [FEATURE] Show the FE user data on the registration confirmation page
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
Labels: enhancement

#2040 [FEATURE] Make the registration form fields configurable
  CHANGELOG.md
  Classes/Configuration/EventRegistrationFlexForms.php
  Classes/Domain/Model/Registration/PaymentTrait.php
  Classes/Service/RegistrationProcessor.php
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
  Tests/Unit/Configuration/EventRegistrationFlexFormsTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
  Tests/Unit/Service/RegistrationProcessorTest.php
Labels: enhancement

#2042 [BUGFIX] Also use the configured "registered themselves" value if hidden
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Labels: bug

#2046 [FEATURE] Add `RegistrationGuard.getVacancies()`
  CHANGELOG.md
  Classes/Service/RegistrationGuard.php
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: enhancement

#2047 [BUGFIX] Fix a typo in a label
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
Labels: bug

#2049 [CLEANUP] Refactor the FronEnd.js and create a Seminars class
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Labels: cleanup

#2055 [CLEANUP] Autoformat the JavaScript
  CHANGELOG.md
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
Labels: cleanup
