Repository oliverklee/ext-seminars, pull requests merged in 2022-12, with the labels that each got.

#2057 [TASK] Undo a DB schema change
  ext_tables.sql
Labels: bug

#2058 [FEATURE] Provide separate inputs for each additional attendee
  CHANGELOG.md
  Classes/Domain/Model/Registration/AttendeesTrait.php
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Templates/EventRegistration/Confirm.html
  Resources/Private/Templates/EventRegistration/New.html
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
Labels: enhancement

#2062 [FEATURE] Allow saving additional registered persons as FE users
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Classes/Domain/Model/Registration/AttendeesTrait.php
  Classes/Service/RegistrationProcessor.php
  Configuration/FlexForms/EventRegistration.xml
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
  Tests/Unit/Service/RegistrationProcessorTest.php
Labels: enhancement

#2063 [TASK] Write upgrade notes
  Documentation/EN/Installation/AddingPagesToTheFrontEnd/Index.rst
  Documentation/EN/Installation/Upgrading.rst
Labels: documentation

#2072 [TASK] Document the onetimeaccount type in the upgrade notes
  Documentation/EN/Installation/Upgrading.rst
Labels: documentation

#2071 [FEATURE] Add an SVG icon for the BE module
  CHANGELOG.md
  Resources/Public/Icons/BackEndModule.gif
  Resources/Public/Icons/BackEndModule.svg
  Resources/Public/Icons/Extension.svg
  ext_tables.php
Labels: enhancement

#2074 [FEATURE] Register the new BE module and add empty template files
  CHANGELOG.md
  Classes/Controller/BackEnd/EventController.php
  Resources/Private/Layouts/BackEndModule.html
  Resources/Private/Templates/BackEnd/Event/Index.html
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
  ext_tables.php
Labels: enhancement

#2076 [FEATURE] Display flash messages in the new BE module
  CHANGELOG.md
  Resources/Private/Layouts/BackEndModule.html
Labels: enhancement

#2077 [FEATURE] Provide access to the page tree UID in the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/EventController.php
  Resources/Private/Templates/BackEnd/Event/Index.html
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
Labels: enhancement

#2078 [FEATURE] Add `EventRepository.findBookableEventsByPageUidInBackEndMode`
  CHANGELOG.md
  Classes/Domain/Repository/Event/EventRepository.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Functional/Domain/Repository/Event/Fixtures/DeletedSingleEventOnPage.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventDateOnPage.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/EventTopicOnPage.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/HiddenSingleEventOnPage.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/SingleEventOnPage.xml
  Tests/Functional/Domain/Repository/Event/Fixtures/TwoSingleEventsOnPage.xml
  phpstan-baseline.neon
Labels: enhancement

#2082 [FEATURE] Make the event list for the FE editor striped
  Resources/Private/Templates/FrontEndEditor/Index.html
Labels: enhancement

#2083 [CLEANUP] Move the BE module debug information to the layout
  Resources/Private/Layouts/BackEndModule.html
  Resources/Private/Templates/BackEnd/Event/Index.html
Labels: cleanup

#2085 [FEATURE] Show a flash message in the BE if no page is selected
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/BackEnd/FlashMessage.html
  Resources/Private/Templates/BackEnd/Event/Index.html
Labels: enhancement

#2088 [FEATURE] List events in the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/EventController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/BackEnd/EventList.html
  Resources/Private/Templates/BackEnd/Event/Index.html
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
Labels: enhancement

#2089 [FEATURE] Add `Event.rawData` and `EventRepository.enrichWithRawData()`
  CHANGELOG.md
  Classes/Domain/Model/Event/Event.php
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Repository/Event/EventRepository.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Functional/Domain/Repository/Event/Fixtures/HiddenSingleEventOnPage.xml
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/EventTopicTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
Labels: enhancement

#2090 [FEATURE] Add record icons to the BE module
  Classes/Controller/BackEnd/EventController.php
  Resources/Private/Partials/BackEnd/EventList.html
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
Labels: enhancement

#2091 [BUGFIX] Fix the camelCase of a FE editor template Fluid variable
  CHANGELOG.md
  Resources/Private/Partials/FrontEndEditor/Form.html
Labels: bug, cleanup

#2092 [CLEANUP] Avoid unnecessary inline notation in the Fluid templates
  CHANGELOG.md
  Resources/Private/Partials/EventDate.html
  Resources/Private/Partials/FrontEndEditor/Form.html
Labels: cleanup

#2093 [CLEANUP] Refactor the BE module Fluid template
  Resources/Private/Partials/BackEnd/EventList.html
Labels: cleanup

#2094 [FEATURE] Add a check for write permissions to the BE module
  CHANGELOG.md
  Classes/BackEnd/Permissions.php
  Resources/Private/Layouts/BackEndModule.html
  Tests/Unit/BackEnd/PermissionsTest.php
Labels: enhancement

#2095 [FEATURE] Add event edit links to the BE module
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/BackEnd/EventList.html
  Resources/Private/Templates/BackEnd/Event/Index.html
Labels: enhancement

#2101 [FEATURE] Add `EventsStatisticsCalculator` and `Event/Statistics`
  CHANGELOG.md
  Classes/Domain/Model/Event/EventDateInterface.php
  Classes/Domain/Model/Event/EventDateTrait.php
  Classes/Domain/Model/Event/EventInterface.php
  Classes/Domain/Model/Event/EventStatistics.php
  Classes/Domain/Model/Event/EventTopic.php
  Classes/Domain/Repository/Registration/RegistrationRepository.php
  Classes/Service/EventStatisticsCalculator.php
  Classes/Service/RegistrationGuard.php
  Tests/Functional/Domain/Repository/Registration/Fixtures/DeletedWaitingListRegistrationWithEvent.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/HiddenWaitingListRegistrationWithEvent.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/TwoMultiSeatWaitingListRegistrationsWithSameEvent.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/TwoWaitingListRegistrationsWithSameEventAndUser.xml
  Tests/Functional/Domain/Repository/Registration/Fixtures/WaitingListRegistrationWithZeroSeats.xml
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/EventStatisticsTest.php
  Tests/Unit/Domain/Model/Event/EventTopicTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
  Tests/Unit/Service/EventStatisticsCalculatorTest.php
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: enhancement

#2103 [CLEANUP] Drop some space preservation from the locallang files
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
Labels: cleanup

#2102 [CLEANUP] Use the event statistics in the `RegistrationGuard`
  CHANGELOG.md
  Classes/Service/RegistrationGuard.php
  Tests/Unit/Service/RegistrationGuardTest.php
Labels: cleanup

#2105 [FEATURE] Show event statistics in the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/EventController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/BackEnd/EventList.html
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
Labels: enhancement

#2109 [FEATURE] Add an events CSV export to the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/EventController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Layouts/BackEndModule.html
  Resources/Private/Templates/BackEnd/Event/Index.html
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
  ext_tables.php
Labels: enhancement

#2113 [FEATURE] Add icons for the event status to the BE module
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/BackEnd/EventList.html
Labels: enhancement

#2114 [BUGFIX] Fix the CSV download in the new BE module in TYPO3 11LTS
  CHANGELOG.md
  Classes/Controller/BackEnd/EventController.php
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
  phpstan-baseline.neon
Labels: bug

#2117 [FEATURE] Add a `RegistrationController` for the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/AbstractController.php
  Classes/Controller/BackEnd/EventController.php
  Classes/Controller/BackEnd/RegistrationController.php
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
  Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
  phpstan-baseline.neon
Labels: enhancement

#2120 [FEATURE] Show event in the registration info in the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/RegistrationController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Layouts/BackEndModule.html
  Resources/Private/Partials/BackEnd/EventList.html
  Resources/Private/Partials/BackEnd/RegistrationStatistics.html
  Resources/Private/Partials/BackEnd/SeatStatistics.html
  Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
  Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
  ext_tables.php
Labels: enhancement

#2123 [FEATURE] Display registrations in the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/RegistrationController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/BackEnd/EventList.html
  Resources/Private/Partials/BackEnd/RegistrationList.html
  Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
  Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
  phpstan-baseline.neon
Labels: enhancement

#2124 [TASK] Make the raw data functionality reusable
  CHANGELOG.md
  Classes/Domain/Model/Event/Event.php
  Classes/Domain/Model/RawDataInterface.php
  Classes/Domain/Model/RawDataTrait.php
  Classes/Domain/Repository/AbstractRawDataCapableRepository.php
  Classes/Domain/Repository/Event/EventRepository.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
  Tests/Unit/Domain/Model/Event/EventDateTest.php
  Tests/Unit/Domain/Model/Event/EventTopicTest.php
  Tests/Unit/Domain/Model/Event/SingleEventTest.php
  Tests/Unit/Domain/Repository/Event/EventRepositoryTest.php
Labels: cleanup

#2125 [FEATURE] Make the `Repository` raw-data-capable
  Classes/Domain/Model/Registration/Registration.php
  Classes/Domain/Repository/Registration/RegistrationRepository.php
  Tests/Functional/Domain/Repository/Registration/RegistrationRepositoryTest.php
  Tests/Unit/Domain/Model/Registration/RegistrationTest.php
  Tests/Unit/Domain/Repository/Registration/RegistrationRepositoryTest.php
Labels: enhancement

#2126 [FEATURE] Display icons for registrations in the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/RegistrationController.php
  Resources/Private/Partials/BackEnd/EventList.html
  Resources/Private/Partials/BackEnd/RegistrationList.html
  Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
Labels: enhancement

#2129 [FEATURE] Add edit icons/links for registrations in the BE module
  CHANGELOG.md
  Resources/Private/Partials/BackEnd/RegistrationList.html
  Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
Labels: enhancement

#2137 [FEATURE] Add button stubs to the BE module
  CHANGELOG.md
  Resources/Private/Partials/BackEnd/EventList.html
  Resources/Private/Partials/BackEnd/RegistrationList.html
Labels: enhancement

#2139 [FEATURE] Add CSV export for registrations to the BE module
  CHANGELOG.md
  Classes/Controller/BackEnd/RegistrationController.php
  Resources/Private/Templates/BackEnd/Event/Index.html
  Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
  Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
  ext_tables.php
  phpstan-baseline.neon
Labels: enhancement

#2147 [CLEANUP] Rename a variable in a repository method
  Classes/Domain/Repository/AbstractRawDataCapableRepository.php
Labels: cleanup

#2151 [FEATURE] Add an email form the backend module
  CHANGELOG.md
  Classes/BackEnd/AbstractEventMailForm.php
  Classes/Controller/BackEnd/EmailController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Partials/BackEnd/EventList.html
  Resources/Private/Templates/BackEnd/Email/Compose.html
  Tests/Unit/Controller/BackEnd/EmailControllerTest.php
  ext_tables.php
Labels: enhancement

#2158 [TASK] Drop the SwiftMailer dependency
  CHANGELOG.md
  Classes/Email/EmailBuilder.php
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/CancelEventMailFormTest.php
  Tests/Functional/BackEnd/ConfirmEventMailFormTest.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/Functional/Service/RegistrationManagerTest.php
  Tests/LegacyUnit/FrontEnd/EventEditorTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/LegacyUnit/SchedulerTasks/RegistrationDigestTest.php
  Tests/LegacyUnit/Service/EmailServiceTest.php
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  Tests/Unit/Email/EmailBuilderTest.php
  Tests/Unit/Traits/EmailTrait.php
  Tests/Unit/Traits/EmailTraitTest.php
  composer.json
Labels: cleanup, dependencies

#2160 [BUGFIX] Use the Core `PageRepository`
  Classes/Bag/AbstractBag.php
  Classes/BagBuilder/AbstractBagBuilder.php
Labels: bug

#2162 [TASK] Drop the V9 badge from the README
  README.md
Labels: documentation

#2163 [TASK] Drop support for Emogrifier 4 and 5
  CHANGELOG.md
  composer.json
Labels: dependencies

#2164 [TASK] Drop `.htaccess` files
  CHANGELOG.md
  Configuration/.htaccess
  Resources/Private/.htaccess
  Tests/.htaccess
Labels: cleanup

#2166 [BUGFIX] Stop using the deprecated `Web\Response` class
  CHANGELOG.md
  Tests/Unit/Controller/BackEnd/EventControllerTest.php
  Tests/Unit/Controller/BackEnd/RegistrationControllerTest.php
Labels: bug, cleanup

#2168 [TASK] Update `ergebnis/composer-normalize`
  .github/dependabot.yml
  composer.json
Labels: dependencies

#2169 [TASK] Update `phpstan/extension-installer`
  .github/dependabot.yml
  composer.json
Labels: dependencies

#2173 [TASK] Remove the crowdfunding campaign ads
  Documentation/EN/Index.rst
  README.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/locallang.xlf
Labels: documentation

#2171 [TASK] Drop obsolete package conflicts
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: cleanup, dependencies

#2174 [TASK] Drop the `typo3/class-alias-loader` dev dependency
  composer.json
Labels: dependencies

#2175 [TASK] Upgrade `saschaegerer/phpstan-typo3 `
  .github/dependabot.yml
  composer.json
  phpstan-baseline.neon
Labels: dependencies

#2177 [TASK] Require TYPO3 CMS >= 10.4.22
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: dependencies

#2178 [TASK] Update the Composer dependencies
  .github/dependabot.yml
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: dependencies

#2183 [BUGFIX] Stop using the deprecated `TYPO3_MODE` as security gate
  CHANGELOG.md
  Configuration/TCA/Overrides/fe_users.php
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TCA/tx_seminars_attendances.php
  Configuration/TCA/tx_seminars_categories.php
  Configuration/TCA/tx_seminars_checkboxes.php
  Configuration/TCA/tx_seminars_event_types.php
  Configuration/TCA/tx_seminars_foods.php
  Configuration/TCA/tx_seminars_lodgings.php
  Configuration/TCA/tx_seminars_organizers.php
  Configuration/TCA/tx_seminars_payment_methods.php
  Configuration/TCA/tx_seminars_seminars.php
  Configuration/TCA/tx_seminars_sites.php
  Configuration/TCA/tx_seminars_skills.php
  Configuration/TCA/tx_seminars_speakers.php
  Configuration/TCA/tx_seminars_target_groups.php
  Configuration/TCA/tx_seminars_test.php
  Configuration/TCA/tx_seminars_timeslots.php
  ext_localconf.php
  ext_tables.php
Labels: bug, cleanup

#2189 [TASK] Add `@covers` annotations to the model and mapper tests
  Tests/LegacyUnit/Mapper/CategoryMapperTest.php
  Tests/LegacyUnit/Mapper/CheckboxMapperTest.php
  Tests/LegacyUnit/Mapper/EventTopicMapperTest.php
  Tests/LegacyUnit/Mapper/FoodMapperTest.php
  Tests/LegacyUnit/Mapper/FrontEndUserGroupMapperTest.php
  Tests/LegacyUnit/Mapper/LodgingMapperTest.php
  Tests/LegacyUnit/Mapper/OrganizerMapperTest.php
  Tests/LegacyUnit/Mapper/PaymentMethodMapperTest.php
  Tests/LegacyUnit/Mapper/PlaceMapperTest.php
  Tests/LegacyUnit/Mapper/SingleEventMapperTest.php
  Tests/LegacyUnit/Mapper/SkillMapperTest.php
  Tests/LegacyUnit/Mapper/SpeakerMapperTest.php
  Tests/LegacyUnit/Mapper/TargetGroupMapperTest.php
  Tests/LegacyUnit/Mapper/TimeSlotMapperTest.php
  Tests/LegacyUnit/Model/AbstractTimeSpanTest.php
  Tests/LegacyUnit/Model/BackEndUserGroupTest.php
  Tests/LegacyUnit/Model/BackEndUserTest.php
  Tests/LegacyUnit/Model/CategoryTest.php
  Tests/LegacyUnit/Model/EventDateTest.php
  Tests/LegacyUnit/Model/EventTest.php
  Tests/LegacyUnit/Model/EventTopicTest.php
  Tests/LegacyUnit/Model/EventTypeTest.php
  Tests/LegacyUnit/Model/FoodTest.php
  Tests/LegacyUnit/Model/FrontEndUserGroupTest.php
  Tests/LegacyUnit/Model/FrontEndUserTest.php
  Tests/LegacyUnit/Model/LodgingTest.php
  Tests/LegacyUnit/Model/OrganizerTest.php
  Tests/LegacyUnit/Model/PaymentMethodTest.php
  Tests/LegacyUnit/Model/SingleEventTest.php
  Tests/LegacyUnit/Model/TimeSlotTest.php
  Tests/Unit/Model/EventTest.php
  Tests/Unit/Model/SkillTest.php
Labels: cleanup

#2197 [TASK] Drop `config.uniqueLinkVars` from the TypoScript
  CHANGELOG.md
  Configuration/TypoScript/Config.typoscript
Labels: cleanup

#2221 [TASK] Drop the custom BE user and BE user group models
  CHANGELOG.md
  Classes/BackEnd/AbstractList.php
  Classes/Mapper/BackEndUserGroupMapper.php
  Classes/Mapper/BackEndUserMapper.php
  Classes/Model/BackEndUser.php
  Classes/Model/BackEndUserGroup.php
  Classes/SchedulerTasks/MailNotifier.php
  Tests/Functional/Mapper/BackEndUserGroupMapperTest.php
  Tests/Functional/Mapper/BackEndUserMapperTest.php
  Tests/LegacyUnit/BackEnd/EventsListTest.php
  Tests/LegacyUnit/Model/BackEndUserGroupTest.php
  Tests/LegacyUnit/Model/BackEndUserTest.php
  Tests/LegacyUnit/SchedulerTasks/MailNotifierTest.php
  Tests/Unit/Mapper/BackEndUserGroupMapperTest.php
  Tests/Unit/Mapper/BackEndUserMapperTest.php
  phpstan-baseline.neon
Labels: cleanup

#2249 [TASK] Add dedicated tests for `GeneralEventMailForm::sendEmailToAttendees`
  CHANGELOG.md
  Tests/Functional/BackEnd/AbstractEventMailFormTest.php
  Tests/Functional/BackEnd/GeneralEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/AbstractEventMailFormTest.php
  Tests/LegacyUnit/BackEnd/GeneralEventMailFormTest.php
Labels: enhancement

#2257 [BUGFIX] Fix crash saving an event in the FE editor
  CHANGELOG.md
  Classes/Domain/Model/Event/EventStatistics.php
  Tests/Functional/Domain/Repository/Event/EventRepositoryTest.php
Labels: bug

#2258 [CLEANUP] Simplify the legacy event tests
  Tests/LegacyUnit/OldModel/LegacyRegistrationTest.php
Labels: cleanup

#2261 [FEATURE] Use SimpleCSS for the email CSS
  CHANGELOG.md
  Resources/Private/CSS/thankYouMail.css
Labels: enhancement

#2262 [BUGFIX] Stop testing for the exact email markup
  CHANGELOG.md
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
Labels: bug

#2266 [TASK] Move `plugin.eventRegistration.heading.eventTitleAndDateAndUid`
  CHANGELOG.md
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Partials/EventTitleAndDateAndUid.html
  Resources/Private/Templates/BackEnd/Email/Compose.html
  Resources/Private/Templates/BackEnd/Registration/ShowForEvent.html
Labels: cleanup

#2270 [TASK] Rename `denyRegistrationAction` to `denyAction`
  CHANGELOG.md
  Classes/Controller/EventRegistrationController.php
  Resources/Private/Templates/EventRegistration/Deny.html
  Tests/Unit/Controller/EventRegistrationControllerTest.php
  ext_localconf.php
Labels: cleanup, templates

#2273 [FEATURE] Rewrite the unregistration form (part 1)
  CHANGELOG.md
  Classes/Controller/EventUnregistrationController.php
  Classes/Service/RegistrationManager.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Layouts/EventUnregistration.html
  Resources/Private/Templates/EventUnregistration/Confirm.html
  Resources/Private/Templates/EventUnregistration/Deny.html
  Tests/Unit/Controller/EventUnregistrationControllerTest.php
  Tests/Unit/Controller/FrontEndEditorControllerTest.php
  ext_localconf.php
Labels: enhancement

#2276 [TASK] Rename `LegacyRegistrationConfiguration` to `LegacyConfiguration`
  CHANGELOG.md
  Classes/Configuration/LegacyConfiguration.php
  Classes/Service/RegistrationProcessor.php
  Tests/Unit/Configuration/LegacyConfigurationTest.php
  Tests/Unit/Service/RegistrationProcessorTest.php
Labels: cleanup

#2277 [FEATURE] Rewrite the unregistration form (part 2)
  CHANGELOG.md
  Classes/Configuration/LegacyConfiguration.php
  Classes/Controller/EventUnregistrationController.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
  Resources/Private/Templates/EventUnregistration/Confirm.html
  Resources/Private/Templates/EventUnregistration/ThankYou.html
  Resources/Public/JavaScript/FrontEnd/FrontEnd.js
  Tests/Unit/Controller/EventUnregistrationControllerTest.php
  ext_localconf.php
Labels: enhancement

#2284 [TASK] Drop the changelog archive
  CHANGELOG.md
  Documentation/changelog-archive.txt
Labels: cleanup, documentation

#2285 [TASK] Drop the Dutch manual for good
  CHANGELOG.md
  Documentation/dutch-manual.pdf
Labels: documentation

#2287 [TASK] Add missing `@covers` annotation
  Tests/Functional/Configuration/RegistrationListConfigurationCheckTest.php
Labels: cleanup

#2295 [TASK] Improve the upgrade notes
  CHANGELOG.md
  Documentation/Installation/InstallingTheExtension/Index.rst
  Documentation/Installation/Upgrading.rst
  Documentation/KnownProblems/Index.rst
Labels: documentation

#2297 [TASK] Use native return types in `EventTypeInterface`
  Classes/Domain/Model/EventTypeInterface.php
Labels: cleanup

#2301 [TASK] Drop obsolete file upload messages
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/dk.locallang.xlf
  Resources/Private/Language/fr.locallang.xlf
  Resources/Private/Language/it.locallang.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/nl.locallang.xlf
  Resources/Private/Language/ru.locallang.xlf
Labels: cleanup

#2300 [TASK] Drop the unused `RegistrationManager::getRegistrationMapper`
  Classes/Service/RegistrationManager.php
Labels: cleanup

#2303 [TASK] Drop obsolete development stuff from the manual
  Documentation/DevelopmentWorkflow/ChangingOrCustomizingTheExtension/Index.rst
  Documentation/DevelopmentWorkflow/DevelopmentWorkflowAndCodingStyleGuidelines/Index.rst
  Documentation/DevelopmentWorkflow/Index.rst
  Documentation/DevelopmentWorkflow/ReleaseChecklist/Index.rst
  Documentation/DevelopmentWorkflow/TheDevelopersMailingListAndWiki/Index.rst
  Documentation/HelpingOut/BuyingSomeWork/Index.rst
  Documentation/HelpingOut/Do-it-yourself/Index.rst
  Documentation/HelpingOut/Index.rst
  Documentation/HelpingOut/ReportingBugs/Index.rst
  Documentation/Index.rst
  Documentation/KeepingUp-to-dateAndGettingSupport/FreePublicSupport/Index.rst
  Documentation/KeepingUp-to-dateAndGettingSupport/Index.rst
  Documentation/KeepingUp-to-dateAndGettingSupport/PaidServicesOfferedByTheAuthor/Index.rst
  Documentation/YourHelpIsWanted/Index.rst
Labels: cleanup, documentation

#2306 [TASK] Drop an unused method from a test
  Tests/LegacyUnit/Service/RegistrationManagerTest.php
  phpstan-baseline.neon
Labels: cleanup

#2310 [TASK] Drop the `externalLinkTarget` setting
  CHANGELOG.md
  Classes/Configuration/SingleViewConfigurationCheck.php
  Configuration/TypoScript/FrontEnd.typoscript
  Documentation/Reference/SetupForTheSeminarManagerFront-endPlug-inInPlugintxSeminarsPi1/Index.rst
Labels: cleanup

#2316 [TASK] Drop the `Event::STATUS_*` constants
  CHANGELOG.md
  Classes/Model/Event.php
  Tests/LegacyUnit/Model/EventTest.php
  phpstan-baseline.neon
Labels: cleanup

#2319 [TASK] Drop obsolete TypoScript related to `sb_accessiblecontent`
  CHANGELOG.md
  Configuration/TypoScript/Content.typoscript
  Configuration/TypoScript/setup.typoscript
Labels: cleanup

#2322 [TASK] Bump the dependencies
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: dependencies

#2325 [FEATURE] Add an upgrade wizard for the separate billing address
  CHANGELOG.md
  Classes/UpgradeWizards/SeparateBillingAddressUpgradeWizard.php
  Tests/Functional/UpgradeWizards/Fixtures/RegistrationWithMarkedBillingAddress.xml
  Tests/Functional/UpgradeWizards/Fixtures/RegistrationWithUnmarkedBillingAddressCity.xml
  Tests/Functional/UpgradeWizards/Fixtures/RegistrationWithoutBillingAddress.xml
  Tests/Functional/UpgradeWizards/SeparateBillingAddressUpgradeWizardTest.php
  Tests/Unit/UpgradeWizards/SeparateBillingAddressUpgradeWizardTest.php
  composer.json
  ext_localconf.php
  phpstan-baseline.neon
Labels: enhancement

#2326 [TASK] Bump the Symfony dependencies
  composer.json
Labels: dependencies

#2328 [FEATURE] Allow installations with TYPO3 11LTS
  CHANGELOG.md
  README.md
  composer.json
  ext_emconf.php
  phpstan-baseline.neon
Labels: enhancement

#2329 [FEATURE] Add TYPO3 11LTS to the test matrix
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: enhancement

#2333 [FEATURE] Add support for PHP 8.1
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: enhancement

#2335 [FEATURE] Add support for PHP 8.2
  .github/workflows/ci.yml
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: enhancement

#2338 [BUGFIX] Fix array access warnings in `SelectorWidget` in PHP 8.1
  CHANGELOG.md
  Classes/FrontEnd/SelectorWidget.php
  phpstan-baseline.neon
Labels: bug

#2340 [BUGFIX] Stop using the deprecated `strftime` in some places
  CHANGELOG.md
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/LegacyTimeSlot.php
  Classes/Service/RegistrationManager.php
  phpstan-baseline.neon
Labels: bug, cleanup

#2346 [FEATURE] Add a date format converter
  CHANGELOG.md
  Classes/Service/DateFormatConverter.php
  Tests/Unit/Service/DateFormatConverterTest.php
Labels: enhancement

#2347 [BUGFIX] Replace usages of `strftime` in the production code
  CHANGELOG.md
  Classes/Configuration/Traits/SharedPluginConfiguration.php
  Classes/OldModel/AbstractTimeSpan.php
  Classes/OldModel/LegacyEvent.php
  Classes/OldModel/LegacyRegistration.php
  Classes/OldModel/LegacyTimeSlot.php
  Classes/Service/RegistrationManager.php
  Classes/ViewHelpers/DateRangeViewHelper.php
  phpstan-baseline.neon
Labels: bug

#2349 [BUGFIX] Avoid array access warnings in `SalutationAwareTranslateViewHelper`
  CHANGELOG.md
  Classes/ViewHelpers/SalutationAwareTranslateViewHelper.php
  phpstan-baseline.neon
Labels: bug

#2356 [BUGFIX] Use Composer 2.4 for the legacy tests on CI
  .github/workflows/ci.yml
Labels: bug

#2353 [TASK] Require oelib >= 5.1.0
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: dependencies

#2358 [TASK] Require feuserextrafields >= 5.3.0
  CHANGELOG.md
  composer.json
  ext_emconf.php
Labels: dependencies

#2360 [TASK] Bump the TYPO3 Console dependencies
  composer.json
Labels: dependencies

#2362 [TASK] Bump typo3/coding-standards
  .github/dependabot.yml
  composer.json
Labels: dependencies

#2368 [BUGFIX] Correct use of the configuration "accessToFrontEndRegistrationLists"
  Classes/FrontEnd/DefaultController.php
  Classes/FrontEnd/RegistrationsList.php
Labels: bug

#2369 [TASK] Add changelog entry
  CHANGELOG.md
Labels: documentation

#2370 [TASK] Make the file name of `csvReponse` required and non-empty
  Classes/Csv/CsvResponse.php
  Tests/Unit/Csv/CsvResponseTest.php
Labels: cleanup
