Repository oliverklee/ext-seminars, pull requests merged in 2023-01, with the labels that each got.

#2374 Replace renderAsRichText() by pi_RTEcssText() method
  Classes/FrontEnd/DefaultController.php
Labels: bug

#2377 [TASK] Add changelog entry
  CHANGELOG.md
Labels: documentation

#2378 [FEATURE] Add a "diverse" gender
  CHANGELOG.md
  Classes/Email/Salutation.php
  Classes/FrontEnd/DefaultController.php
  Classes/Model/Registration.php
  Classes/OldModel/LegacyEvent.php
  Classes/OldModel/LegacySpeaker.php
  Configuration/TCA/tx_seminars_attendances.php
  Resources/Private/Language/de.locallang.xlf
  Resources/Private/Language/de.locallang_db.xlf
  Resources/Private/Language/locallang.xlf
  Resources/Private/Language/locallang_db.xlf
  Tests/Functional/OldModel/LegacyRegistrationTest.php
  Tests/LegacyUnit/Model/RegistrationTest.php
Labels: enhancement

#2384 [TASK] Change copyright year
  Documentation/Index.rst
  Documentation/Settings.yml
Labels: documentation
